### ISSUE TITLE
[Bug] Problem with the handling of unicode strings prevents XML generation

### ISSUE THREAD

**Issue by benji1000** [nabla-c0d3/sslyze#110]
Hello,

this is a nasty one: when I run SSLyze 0.12 with the option --xml_out on a website I want to test, it sometimes fails with this error: <code>UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 10: ordinal not in range(128)</code>.

The traceback:

<pre>Traceback (most recent call last):
  File "/etc/sslyze/sslyze.py", line 348, in <module>
    main()
  File "/etc/sslyze/sslyze.py", line 327, in main
    xml_final_string = tostring(xml_final_doc, encoding='UTF-8')
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 932, in _serialize_xml
    v = _escape_attrib(v, encoding)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1090, in _escape_attrib
    return text.encode(encoding, "xmlcharrefreplace")</pre>

The command I was launching, with Python 2.7.9 first then 2.7.11:

<code>python /etc/sslyze/sslyze.py --regular --hsts --xml_out scan.xm some-website.com:443</code>

It has to deal with unicode and the way they are handled in Python. I think this website can help you get your head around the problem: http://farmdev.com/talks/unicode/.

This is actually a blocking issue since it prevents the user to scan and generate XML output for some hosts. Please contact me if you want to have some hosts for which this problem occurs.

Thank you in advance for looking into this issue!

**Comment by nabla-c0d3** [comment]
Hi,
Thanks for the bug report - can you send me the hosts ? My email is on my github profile.

**Comment by nabla-c0d3** [comment]
Fixed in aec1a4357c4242b034cb547146ebeb6a79503121

**Comment by benji1000** [comment]
Nice, thanks!
