### ISSUE TITLE
as_dict bug when parsing utf-16 encoded subject/issuer certificate fields

### ISSUE THREAD

**Issue by kacpern** [nabla-c0d3/sslyze#179]
When converting a x509 cert to dict with `as_dict` there is an overflow of data. Surprisingly `as_text` works correctly.

Example certificate: https://gooseneck.globusfamily.com.au

In this example the issuer is an UTF16-BE encoded value:
`'\x00{\x007\x00E\x00F\x002\x00B\x001\x005\x00E\x00-\x006\x00A\x006\x002\x00-\x004\x005\x008\x008\x00-\x00B\x006\x001\x00E\x00-\x003\x00C\x00B\x00F\x004\x001\x006\x00F\x00A\x001\x005\x005\x00}'`

The parsed value is:
`'{7EF2B15E-6A62-4588-B61E-3CBF416FA155}  U�e �{7EF2B15E-6A62-4588-B61E-3CB'`

Seems the bug is in the C code.

Ideas?

**Comment by kacpern** [comment]
I'm sorry, but this is most likely a bug in nassl, rather then sslyze. Do you want me to open an issue in the other repo?

**Comment by nabla-c0d3** [comment]
Thanks. I think it's in SSLyze so please leave it here. Same issue with the XML output:

> Traceback (most recent call last):
  File "sslyze_cli.py", line 689, in <module>
    main()
  File "sslyze_cli.py", line 596, in main
    xml_output_list.append(_format_xml_target_result(server_info, result_list))
  File "sslyze_cli.py", line 413, in _format_xml_target_result
    target_xml.append(plugin_result.as_xml())
  File "/Users/nabla/Documents/github/sslyze/sslyze/plugins/certificate_info_plugin.py", line 525, in as_xml
    cert_xml.append(_keyvalue_pair_to_xml(key, value))
  File "/Users/nabla/Documents/github/sslyze/sslyze/plugins/certificate_info_plugin.py", line 710, in _keyvalue_pair_to_xml
    key_xml.append(_keyvalue_pair_to_xml(subkey, value[subkey]))
  File "/Users/nabla/Documents/github/sslyze/sslyze/plugins/certificate_info_plugin.py", line 694, in _keyvalue_pair_to_xml
    key_xml = _create_xml_node(key, value)
  File "/Users/nabla/Documents/github/sslyze/sslyze/plugins/certificate_info_plugin.py", line 687, in _create_xml_node
    xml_node.text = value.decode("utf-8").strip()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd0 in position 55: invalid continuation byte

**Comment by kacpern** [comment]
As far as I can tell this is the culprit: https://github.com/nabla-c0d3/nassl/blob/master/nassl/x509_certificate.py#L186

**Comment by nabla-c0d3** [comment]
Fixed by 876b340763f9581e62e9d168079c27cf2feb7742
