### ISSUE TITLE
XML serialization fails when scanning through a HTTP proxy

### ISSUE THREAD

**Issue by hypn0s** [nabla-c0d3/sslyze#188]
Hello, I have issues when I try to scan through a HTTP proxy, sslyze does not get the IP of the scanned server and it fails at the XML serialization step:

```
$ python -m sslyze --regular --https_tunnel=http://127.0.0.1:3128 --xml_out=test www.google.fr
...
 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   www.google.fr:443                       => None



 SCAN RESULTS FOR WWW.GOOGLE.FR:443 - NONE:443
 ---------------------------------------------
...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/hypn0s/github/sslyze/sslyze/__main__.py", line 689, in <module>
    main()
  File "/home/hypn0s/github/sslyze/sslyze/__main__.py", line 668, in main
    xml_final_string = tostring(xml_final_doc, encoding='UTF-8')
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 932, in _serialize_xml
    v = _escape_attrib(v, encoding)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1092, in _escape_attrib
    _raise_serialization_error(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1052, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize None (type NoneType)

```

Maybe a solution could be to resolve the hostname if possible, otherwise set an empty string, I don't really know what's best.

**Comment by nabla-c0d3** [comment]
Thanks for the report
