### ISSUE TITLE
1.0.0 python run_tests.py failures

### ISSUE THREAD

**Issue by ilovezfs** [nabla-c0d3/sslyze#192]
I'm seeing these two errors and two failures when running `python run_tests.py`:
```
======================================================================
ERROR: test_unicode_certificate (plugin_tests.test_certificate_info_plugin.CertificateInfoPluginTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sslyze-20170213-14808-18m8mim/sslyze-1.0.0/tests/plugin_tests/test_certificate_info_plugin.py", line 146, in test_unicode_certificate
    plugin_result = plugin.process_task(server_info, CertificateInfoScanCommand())
  File "/private/tmp/sslyze-20170213-14808-18m8mim/sslyze-1.0.0/sslyze/plugins/certificate_info_plugin.py", line 151, in process_task
    raise RuntimeError(u'Could not connect to the server; last error: {}'.format(last_exception))
RuntimeError: Could not connect to the server; last error: TCP / Received RST

======================================================================
ERROR: test_follows_client_cipher_suite_preference (plugin_tests.test_openssl_cipher_suites_plugin.OpenSslCipherSuitesPluginTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sslyze-20170213-14808-18m8mim/sslyze-1.0.0/tests/plugin_tests/test_openssl_cipher_suites_plugin.py", line 199, in test_follows_client_cipher_suite_preference
    plugin_result = plugin.process_task(server_info, Tlsv12ScanCommand())
  File "/private/tmp/sslyze-20170213-14808-18m8mim/sslyze-1.0.0/sslyze/plugins/openssl_cipher_suites_plugin.py", line 167, in process_task
    preferred_cipher = self._get_preferred_cipher_suite(server_connectivity_info, ssl_version, accepted_cipher_list)
  File "/private/tmp/sslyze-20170213-14808-18m8mim/sslyze-1.0.0/sslyze/plugins/openssl_cipher_suites_plugin.py", line 215, in _get_preferred_cipher_suite
    second_cipher = self._get_selected_cipher_suite(server_connectivity_info, ssl_version, second_cipher_string)
  File "/private/tmp/sslyze-20170213-14808-18m8mim/sslyze-1.0.0/sslyze/plugins/openssl_cipher_suites_plugin.py", line 235, in _get_selected_cipher_suite
    ssl_connection.connect()
  File "/private/tmp/sslyze-20170213-14808-18m8mim/sslyze-1.0.0/sslyze/utils/ssl_connection.py", line 166, in connect
    self.do_handshake()
  File "/usr/local/Cellar/sslyze/1.0.0/libexec/lib/python2.7/site-packages/nassl/ssl_client.py", line 144, in do_handshake
    handshake_data_in = self._sock.recv(self._DEFAULT_BUFFER_SIZE)
timeout: timed out

======================================================================
FAIL: test_not_trusted_by_mozilla_but_trusted_by_apple (plugin_tests.test_certificate_info_plugin.CertificateInfoPluginTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sslyze-20170213-14808-18m8mim/sslyze-1.0.0/tests/plugin_tests/test_certificate_info_plugin.py", line 174, in test_not_trusted_by_mozilla_but_trusted_by_apple
    self.assertEqual(plugin_result.successful_trust_store.name, u'Apple')
AssertionError: u'Microsoft' != u'Apple'
- Microsoft
+ Apple


======================================================================
FAIL: test_tlsv1_2_enabled (plugin_tests.test_openssl_cipher_suites_plugin.OpenSslCipherSuitesPluginTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sslyze-20170213-14808-18m8mim/sslyze-1.0.0/tests/plugin_tests/test_openssl_cipher_suites_plugin.py", line 113, in test_tlsv1_2_enabled
    set(accepted_cipher_name_list))
AssertionError: Items in the first set but not the second:
'TLS_RSA_WITH_AES_128_CBC_SHA256'
'TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256'
'OLD_TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256'
'TLS_RSA_WITH_AES_256_CBC_SHA256'
'TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384'

----------------------------------------------------------------------
Ran 64 tests in 131.530s

FAILED (failures=2, errors=2)
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: python run_tests.py
```

**Comment by nabla-c0d3** [comment]
Are you running the tests on Windows 64 ? The last one will always on that platform. The first two are connectivity issues and I an fix the third one.

**Comment by ilovezfs** [comment]
This is macOS 10.11.6

**Comment by ilovezfs** [comment]
The above was running the tests locally.

Here are the logs from the CI boxes:
https://bot.brew.sh/job/Homebrew%20Core/16490/version=sierra/console
https://bot.brew.sh/job/Homebrew%20Core/16490/version=el_capitan/console
https://bot.brew.sh/job/Homebrew%20Core/16490/version=yosemite/console

So `test_not_trusted_by_mozilla_but_trusted_by_apple` fails on 10.11 and 10.10 but not on 10.12. And 10.12 had the failure
```
======================================================================
ERROR: test_1000_sans_chain (plugin_tests.test_certificate_info_plugin.CertificateInfoPluginTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sslyze-20170215-78349-nmc9mi/sslyze-1.0.0/tests/plugin_tests/test_certificate_info_plugin.py", line 104, in test_1000_sans_chain
    server_info.test_connectivity_to_server()
  File "/private/tmp/sslyze-20170215-78349-nmc9mi/sslyze-1.0.0/sslyze/server_connectivity.py", line 191, in test_connectivity_to_server
    raise ServerConnectivityError(self.CONNECTIVITY_ERROR_REJECTED)
ServerConnectivityError
```

**Comment by nabla-c0d3** [comment]
The tests should be fixed now - can you confirm?

**Comment by ilovezfs** [comment]
locally I'm seeing
```

======================================================================
ERROR: test (plugin_tests.test_trust_store.TrustStoreTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sslyze-20170217-72245-13nl90o/tests/plugin_tests/test_trust_store.py", line 23, in test
    verified_chain = trust_store.build_verified_certificate_chain(certificate_chain)
  File "/private/tmp/sslyze-20170217-72245-13nl90o/sslyze/plugins/utils/trust_store/trust_store.py", line 128, in build_verified_certificate_chain
    anchor_cert = self._get_certificate_with_subject(cert.as_dict[u'issuer'])
  File "/private/tmp/sslyze-20170217-72245-13nl90o/sslyze/plugins/utils/trust_store/trust_store.py", line 87, in _get_certificate_with_subject
    self._subject_to_certificate_dict = self._compute_subject_certificate_dict()
  File "/private/tmp/sslyze-20170217-72245-13nl90o/sslyze/plugins/utils/trust_store/trust_store.py", line 66, in _compute_subject_certificate_dict
    cert_dict[self._hash_subject(cert.as_dict[u'subject'])] = cert
  File "/private/tmp/sslyze-20170217-72245-13nl90o/sslyze/plugins/utils/trust_store/trust_store.py", line 79, in _hash_subject
    decoded_value = value.decode(encoding=u'utf-16')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_16.py", line 16, in decode
    return codecs.utf_16_decode(input, errors, True)
UnicodeDecodeError: 'utf16' codec can't decode bytes in position 72-73: illegal encoding

----------------------------------------------------------------------
Ran 64 tests in 65.231s

FAILED (errors=1)
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: python run_tests.py
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

Test is now running on CI as well: https://bot.brew.sh/job/Homebrew%20Core/16630/

**Comment by ilovezfs** [comment]
And locally using
```

    resource "nassl" do
      url "https://github.com/nabla-c0d3/nassl/archive/0.15.1.tar.gz"
      sha256 "b25020074d0838837531b2ed30635ec715f60e13f11f416a89588edd08653f1f"
    end

    resource "openssl" do
      url "https://github.com/PeterMosmans/openssl.git",
          :revision => "2622e9bff72f4949c285f2d955c2f78663d79776"
    end
```
instead of
```
    resource "nassl" do
      url "https://github.com/nabla-c0d3/nassl.git"
    end

    resource "openssl" do
      url "https://github.com/PeterMosmans/openssl.git",
          :branch => "1.0.2-chacha"
    end
```
I see
```
test_verify_cert_error_string (X509_Tests.X509_Tests_Online) ... ok

======================================================================
ERROR: test_as_text (OCSP_RESPONSE_Tests.OCSP_RESPONSE_Tests_Online)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sslyze--nassl-20170217-94461-13ecpmn/nassl-0.15.1/tests/OCSP_RESPONSE_Tests.py", line 25, in setUp
    self.ocsp_response = ssl_client.get_tlsext_status_ocsp_resp()._ocsp_response
AttributeError: 'NoneType' object has no attribute '_ocsp_response'

----------------------------------------------------------------------
Ran 86 tests in 1.275s

FAILED (errors=1)
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: python run_tests.py
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

**Comment by ilovezfs** [comment]
On CI, ce662d0b9c88d1fbbce97a4c79dc5864978ab5fc +  https://github.com/nabla-c0d3/nassl/archive/0.15.1.tar.gz + "https://github.com/PeterMosmans/openssl.git",:revision => "2622e9bff72f4949c285f2d955c2f78663d79776" was successful: https://bot.brew.sh/job/Homebrew%20Core/16630/

On CI, ce662d0b9c88d1fbbce97a4c79dc5864978ab5fc + https://github.com/nabla-c0d3/nassl.git + https://github.com/PeterMosmans/openssl.git, :branch => "1.0.2-chacha" had some failures:
https://bot.brew.sh/job/Homebrew%20Core/16632/
https://bot.brew.sh/job/Homebrew%20Core/16632/version=el_capitan/console
https://bot.brew.sh/job/Homebrew%20Core/16632/version=yosemite/console
```
ERROR: test_unicode_certificate (plugin_tests.test_certificate_info_plugin.CertificateInfoPluginTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sslyze-20170217-63244-16nql8d/tests/plugin_tests/test_certificate_info_plugin.py", line 146, in test_unicode_certificate
    plugin_result = plugin.process_task(server_info, CertificateInfoScanCommand())
  File "/private/tmp/sslyze-20170217-63244-16nql8d/sslyze/plugins/certificate_info_plugin.py", line 151, in process_task
    raise RuntimeError(u'Could not connect to the server; last error: {}'.format(last_exception))
RuntimeError: Could not connect to the server; last error: TCP / Received RST
```

**Comment by ilovezfs** [comment]
I ran On CI, ce662d0 + https://github.com/nabla-c0d3/nassl/archive/0.15.1.tar.gz + "https://github.com/PeterMosmans/openssl.git",:revision => "2622e9bff72f4949c285f2d955c2f78663d79776"  through CI again, and this time it turned up one failure:
https://bot.brew.sh/job/Homebrew%20Core/16633/
https://bot.brew.sh/job/Homebrew%20Core/16633/version=yosemite/console
```
ERROR: test (plugin_tests.test_trust_store.TrustStoreTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sslyze-20170217-37192-1k65qm6/tests/plugin_tests/test_trust_store.py", line 23, in test
    verified_chain = trust_store.build_verified_certificate_chain(certificate_chain)
  File "/private/tmp/sslyze-20170217-37192-1k65qm6/sslyze/plugins/utils/trust_store/trust_store.py", line 128, in build_verified_certificate_chain
    anchor_cert = self._get_certificate_with_subject(cert.as_dict[u'issuer'])
  File "/private/tmp/sslyze-20170217-37192-1k65qm6/sslyze/plugins/utils/trust_store/trust_store.py", line 87, in _get_certificate_with_subject
    self._subject_to_certificate_dict = self._compute_subject_certificate_dict()
  File "/private/tmp/sslyze-20170217-37192-1k65qm6/sslyze/plugins/utils/trust_store/trust_store.py", line 66, in _compute_subject_certificate_dict
    cert_dict[self._hash_subject(cert.as_dict[u'subject'])] = cert
  File "/private/tmp/sslyze-20170217-37192-1k65qm6/sslyze/plugins/utils/trust_store/trust_store.py", line 79, in _hash_subject
    decoded_value = value.decode(encoding=u'utf-16')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_16.py", line 16, in decode
    return codecs.utf_16_decode(input, errors, True)
UnicodeDecodeError: 'utf16' codec can't decode bytes in position 122-123: illegal encoding
```

**Comment by nabla-c0d3** [comment]
Thanks for looking into this. 
I can't support older versions of macOS. 
I will release a new version with the fix for `test_not_trusted_by_mozilla_but_trusted_by_apple` (but still want to a wait a bit to see if there are other bugs). The connectivity errors are because the box failed to connect to the server; it is the downside of using live hosts in the test suite.

**Comment by ilovezfs** [comment]
which macOS would you like to be the minimum requirement?

**Comment by nabla-c0d3** [comment]
I only test SSLyze on the latest version (so right now it would be macOS Sierra).

**Comment by ilovezfs** [comment]
So we can probably just limit running the test-suite `if MacOS.version >= :sierra` to avoid false positives.

**Comment by nabla-c0d3** [comment]
The `16632` runs only failed because of a connectivity issue, so it looks like SSLyze might work fine on Yosemite / El Capitan? Not sure what happened with `16633` (but it looks like it was a custom build?).

**Comment by ilovezfs** [comment]
Here's how we build it: https://github.com/Homebrew/homebrew-core/blob/master/Formula/sslyze.rb

https://bot.brew.sh/job/Homebrew%20Core/16630/ and https://bot.brew.sh/job/Homebrew%20Core/16633/ should have been identical, so I think that 16633 is some kind of intermittent failure.

**Comment by nabla-c0d3** [comment]
Can you try again with 1.1.0? Feel free to re-open this issue if it still fails.

**Comment by ilovezfs** [comment]
@nabla-c0d3 with 1.1.0, testing locally I see an intermittent failure like this:
```
======================================================================
ERROR: test_unicode_certificate (plugin_tests.test_certificate_info_plugin.CertificateInfoPluginTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sslyze-20170415-47898-1iqj2a7/sslyze-1.1.0/tests/plugin_tests/test_certificate_info_plugin.py", line 145, in test_unicode_certificate
    plugin_result = plugin.process_task(server_info, CertificateInfoScanCommand())
  File "/private/tmp/sslyze-20170415-47898-1iqj2a7/sslyze-1.1.0/sslyze/plugins/certificate_info_plugin.py", line 155, in process_task
    raise last_exception
SSLHandshakeRejected: TCP / Received RST

----------------------------------------------------------------------
```

**Comment by ilovezfs** [comment]
@nabla-c0d3 re-opened here https://github.com/nabla-c0d3/sslyze/issues/207 because it failed on CI, too.
