### ISSUE TITLE
TypeError: cannot serialize 63072000 (type int)

### ISSUE THREAD

**Issue by kravietz** [nabla-c0d3/sslyze#194]
This:
```
$ sslyze --regular --http_headers --sni=ipsec.pl --json_out=out.json --xml_out=out.xml ipsec.pl
...
Traceback (most recent call last):
  File "/usr/local/bin/sslyze", line 9, in <module>
    load_entry_point('SSLyze==1.0.0', 'console_scripts', 'sslyze')()
  File "/usr/local/lib/python2.7/dist-packages/sslyze/__main__.py", line 134, in main
    output_hub.scans_completed(exec_time)
  File "/usr/local/lib/python2.7/dist-packages/sslyze/cli/output_hub.py", line 58, in scans_completed
    out_generator.scans_completed(total_scan_time)
  File "/usr/local/lib/python2.7/dist-packages/sslyze/cli/xml_output.py", line 92, in scans_completed
    xml_final_string = tostring(self._xml_root_node, encoding='UTF-8')
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 932, in _serialize_xml
    v = _escape_attrib(v, encoding)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1092, in _escape_attrib
    _raise_serialization_error(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1052, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize 63072000 (type int)
```

**Comment by pfreitag** [comment]
Also had this issue, it only seams to happen if you specify `--http_headers`

**Comment by asana12** [comment]
Same problem:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/ns/nscti/lib3rd/sslyze/sslyze/__main__.py", line 138, in <module>
    main()
  File "/usr/local/ns/nscti/lib3rd/sslyze/sslyze/__main__.py", line 134, in main
    output_hub.scans_completed(exec_time)
  File "sslyze/cli/output_hub.py", line 58, in scans_completed
    out_generator.scans_completed(total_scan_time)
  File "sslyze/cli/xml_output.py", line 92, in scans_completed
    xml_final_string = tostring(self._xml_root_node, encoding='UTF-8')
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1126, in tostring
    ElementTree(element).write(file, encoding, method=method)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 820, in write
    serialize(write, self._root, encoding, qnames, namespaces)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 939, in _serialize_xml
    _serialize_xml(write, e, encoding, qnames, None)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 932, in _serialize_xml
    v = _escape_attrib(v, encoding)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1092, in _escape_attrib
    _raise_serialization_error(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1052, in _raise_serialization_error
    "cannot serialize %r (type %s)" % (text, type(text).__name__)
TypeError: cannot serialize 31536000 (type int)`
