### ISSUE TITLE
HTTP Headers plugin fails on verifying certificate chain in Py3 branch

### ISSUE THREAD

**Issue by freakboy3742** [nabla-c0d3/sslyze#199]
The Py3 branch has worked flawlessly for me, except for the HTTP Headers test:

```
(sslyze) hammer:sslyze rkm$ sslyze --http_headers google.com



 AVAILABLE PLUGINS
 -----------------

  OpenSslCipherSuitesPlugin
  OpenSslCcsInjectionPlugin
  HttpHeadersPlugin
  SessionRenegotiationPlugin
  FallbackScsvPlugin
  HeartbleedPlugin
  SessionResumptionPlugin
  CompressionPlugin
  CertificateInfoPlugin



 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   google.com:443                       => 172.217.25.142 



 SCAN RESULTS FOR GOOGLE.COM:443 - 172.217.25.142
 ------------------------------------------------

Unhandled exception while running --http_headers:
NameError - global name 'Certificate' is not defined


 SCAN COMPLETED IN 0.66 S
 ------------------------
```

If you invoke the API directly, you get:

```
Traceback (most recent call last):
  File "probe.py", line 160, in <module>
    probe(sys.argv[1])
  File "probe.py", line 153, in probe
    http_headers(plugins_repository, server_info)
  File "probe.py", line 108, in http_headers
    result = plugin.process_task(server_info, cmd)
  File "/Users/rkm/projects/jambonsw/sslyze/sslyze/plugins/http_headers_plugin.py", line 47, in process_task
    certificate_chain)
  File "/Users/rkm/projects/jambonsw/sslyze/sslyze/plugins/http_headers_plugin.py", line 179, in __init__
    parsed_certificate_chain = [Certificate.from_nassl(x509_cert) for x509_cert in cert_chain]
NameError: global name 'Certificate' is not defined
```

It appears that the plugin hasn't been updated to use the new approach to certificate handling.

**Comment by nabla-c0d3** [comment]
This is the last plugin that I haven't updated for Python3 yet. The whole `python3` branch is still under development as you can tell. 
Only had one question in the PR and then I'll merge it. Thanks for the help!
