### ISSUE TITLE
test_unicode_certificate fails on macOS

### ISSUE THREAD

**Issue by ilovezfs** [nabla-c0d3/sslyze#207]
On all three CI nodes (macOS 10.10, 10.11, and 10.12), I get the following failure during `python run_tests.py` for sslyze 1.1.0:
```
ERROR: test_unicode_certificate (plugin_tests.test_certificate_info_plugin.CertificateInfoPluginTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/tmp/sslyze-20170416-91427-rzr0t8/sslyze-1.1.0/tests/plugin_tests/test_certificate_info_plugin.py", line 145, in test_unicode_certificate
    plugin_result = plugin.process_task(server_info, CertificateInfoScanCommand())
  File "/private/tmp/sslyze-20170416-91427-rzr0t8/sslyze-1.1.0/sslyze/plugins/certificate_info_plugin.py", line 155, in process_task
    raise last_exception
SSLHandshakeRejected: TCP / Received RST

----------------------------------------------------------------------
```
See https://bot.brew.sh/job/Homebrew/job/homebrew-core/job/PR-12496/3/

**Comment by nabla-c0d3** [comment]
It's because this domain is a bit flaky (but usually works) - I might have to find a different one.
