### ISSUE TITLE
Crashes on text display of Elliptic Curve public keys

### ISSUE THREAD

**Issue by konklone** [nabla-c0d3/sslyze#215]
In the latest published version of sslyze:

```
$ sslyze --version
1.1.0
```

The text display crashes when it's displaying cert info for a site that uses an EC public key:

```
$ sslyze --regular green.gov 



 AVAILABLE PLUGINS
 -----------------

  FallbackScsvPlugin
  SessionResumptionPlugin
  SessionRenegotiationPlugin
  CompressionPlugin
  CertificateInfoPlugin
  OpenSslCipherSuitesPlugin
  HttpHeadersPlugin
  HeartbleedPlugin
  OpenSslCcsInjectionPlugin



 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   green.gov:443                       => 23.7.245.8 




Traceback (most recent call last):
  File "/home/eric/.pyenv/versions/2.7.11/bin/sslyze", line 11, in <module>
    load_entry_point('SSLyze==1.1.0', 'console_scripts', 'sslyze')()
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/sslyze/__main__.py", line 132, in main
    output_hub.server_scan_completed(CompletedServerScan(server_info, plugin_result_list))
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/sslyze/cli/output_hub.py", line 57, in server_scan_completed
    out_generator.server_scan_completed(server_scan_result)
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/sslyze/cli/console_output.py", line 76, in server_scan_completed
    for line in plugin_result.as_text():
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/sslyze/plugins/certificate_info_plugin.py", line 343, in as_text
    text_output.extend(self._get_basic_certificate_text())
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/sslyze/plugins/certificate_info_plugin.py", line 577, in _get_basic_certificate_text
    self._format_field('Key Size:', public_key.key_size)]
AttributeError: '_EllipticCurvePublicKey' object has no attribute 'key_size'
```

**Comment by konklone** [comment]
I filed a corresponding bug to the `cryptography` module, since it looks like their API is inconsistent: https://github.com/pyca/cryptography/issues/3540

However, this may be workaroundable with `public_key.curve.key_size` for EC keys in the meantime.

cc @alex
