### ISSUE TITLE
Unhandled exception with InvalidCodepoint error

### ISSUE THREAD

**Issue by konklone** [nabla-c0d3/sslyze#216]
When running this with sslyze 1.1.0:

```
sslyze --regular safetyact.gov
```

I get this in the middle of the text response:

```
Unhandled exception while running --certinfo:
InvalidCodepoint - Codepoint U+003A at position 6 of u'https://www' not allowed
```

And this appears at the end of the text response:

```
Unhandled exception while running --heartbleed:
timeout - timed out
```
Here's the full scan response, so the text is in context:

```
$ sslyze --regular safetyact.gov



 AVAILABLE PLUGINS
 -----------------

  FallbackScsvPlugin
  CompressionPlugin
  SessionRenegotiationPlugin
  SessionResumptionPlugin
  CertificateInfoPlugin
  OpenSslCipherSuitesPlugin
  HttpHeadersPlugin
  HeartbleedPlugin
  OpenSslCcsInjectionPlugin



 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   safetyact.gov:443                       => 216.81.81.241 




 SCAN RESULTS FOR SAFETYACT.GOV:443 - 216.81.81.241
 --------------------------------------------------

  * SSLV2 Cipher Suites:
      Server rejected all cipher suites.

  * Session Renegotiation:
      Client-initiated Renegotiation:    OK - Rejected
      Secure Renegotiation:              OK - Supported

  * Downgrade Attacks:
      TLS_FALLBACK_SCSV:                 OK - Supported

Unhandled exception while running --certinfo:
InvalidCodepoint - Codepoint U+003A at position 6 of u'https://www' not allowed

  * SSLV3 Cipher Suites:
      Server rejected all cipher suites.

  * Deflate Compression:
                                         OK - Compression disabled

  * TLSV1_1 Cipher Suites:
      Preferred:                       
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                ECDH-256 bits  256 bits      HTTP 200 OK                                                 
      Accepted:                        
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                ECDH-256 bits  256 bits      HTTP 200 OK                                                 
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA                  DH-2048 bits   256 bits      HTTP 200 OK                                                 

  * TLSV1_2 Cipher Suites:
      Preferred:                       
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             ECDH-256 bits  256 bits      HTTP 200 OK                                                 
      Accepted:                        
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384             ECDH-256 bits  256 bits      HTTP 200 OK                                                 
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             ECDH-256 bits  256 bits      HTTP 200 OK                                                 
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                ECDH-256 bits  256 bits      HTTP 200 OK                                                 
        TLS_DHE_RSA_WITH_AES_256_GCM_SHA384               DH-2048 bits   256 bits      HTTP 200 OK                                                 
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA256               DH-2048 bits   256 bits      HTTP 200 OK                                                 
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA                  DH-2048 bits   256 bits      HTTP 200 OK                                                 
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             ECDH-256 bits  128 bits      HTTP 200 OK                                                 

  * Resumption Rate:
      With Session IDs:                  OK - Supported (5 successful, 0 failed, 0 errors, 5 total attempts).
      With TLS Tickets:                  OK - Supported

  * TLSV1 Cipher Suites:
      Preferred:                       
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                ECDH-256 bits  256 bits      HTTP 200 OK                                                 
      Accepted:                        
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA                  DH-2048 bits   256 bits      HTTP 200 OK                                                 
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                ECDH-256 bits  256 bits      HTTP 200 OK                                                 

  * OpenSSL CCS Injection:
                                         OK - Not vulnerable to OpenSSL CCS injection

Unhandled exception while running --heartbleed:
timeout - timed out


 SCAN COMPLETED IN 6.29 S
 ------------------------
```

**Comment by konklone** [comment]
I can also get `sslyze` to fully crash if I add the `--json_out` flag, which may give more information:

```
sslyze --regular safetyact.gov --json_out=test.json
```

```
 AVAILABLE PLUGINS
 -----------------

  CompressionPlugin
  HttpHeadersPlugin
  OpenSslCcsInjectionPlugin
  SessionRenegotiationPlugin
  CertificateInfoPlugin
  FallbackScsvPlugin
  HeartbleedPlugin
  OpenSslCipherSuitesPlugin
  SessionResumptionPlugin



 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   safetyact.gov:443                       => 216.81.81.241 




 SCAN RESULTS FOR SAFETYACT.GOV:443 - 216.81.81.241
 --------------------------------------------------

  * Downgrade Attacks:
      TLS_FALLBACK_SCSV:                 OK - Supported

  * SSLV2 Cipher Suites:
      Server rejected all cipher suites.

  * OpenSSL CCS Injection:
                                         OK - Not vulnerable to OpenSSL CCS injection

  * SSLV3 Cipher Suites:
      Server rejected all cipher suites.

  * TLSV1 Cipher Suites:
      Preferred:                       
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                ECDH-256 bits  256 bits      HTTP 200 OK                                                 
      Accepted:                        
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                ECDH-256 bits  256 bits      HTTP 200 OK                                                 
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA                  DH-2048 bits   256 bits      HTTP 200 OK                                                 

  * Session Renegotiation:
      Client-initiated Renegotiation:    OK - Rejected
      Secure Renegotiation:              OK - Supported

Unhandled exception while running --certinfo:
InvalidCodepoint - Codepoint U+003A at position 6 of u'https://www' not allowed

  * Deflate Compression:
                                         OK - Compression disabled

  * Resumption Rate:
      With Session IDs:                  OK - Supported (5 successful, 0 failed, 0 errors, 5 total attempts).
      With TLS Tickets:                  OK - Supported

  * TLSV1_1 Cipher Suites:
      Preferred:                       
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                ECDH-256 bits  256 bits      HTTP 200 OK                                                 
      Accepted:                        
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                ECDH-256 bits  256 bits      HTTP 200 OK                                                 
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA                  DH-2048 bits   256 bits      HTTP 200 OK                                                 

  * TLSV1_2 Cipher Suites:
      Preferred:                       
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             ECDH-256 bits  256 bits      HTTP 200 OK                                                 
      Accepted:                        
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             ECDH-256 bits  256 bits      HTTP 200 OK                                                 
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384             ECDH-256 bits  256 bits      HTTP 200 OK                                                 
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                ECDH-256 bits  256 bits      HTTP 200 OK                                                 
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA256               DH-2048 bits   256 bits      HTTP 200 OK                                                 
        TLS_DHE_RSA_WITH_AES_256_GCM_SHA384               DH-2048 bits   256 bits      HTTP 200 OK                                                 
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA                  DH-2048 bits   256 bits      HTTP 200 OK                                                 
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             ECDH-256 bits  128 bits      HTTP 200 OK                                                 

Unhandled exception while running --heartbleed:
timeout - timed out


 SCAN COMPLETED IN 5.33 S
 ------------------------
Traceback (most recent call last):
  File "/home/eric/.pyenv/versions/2.7.11/bin/sslyze", line 11, in <module>
    load_entry_point('SSLyze==1.1.0', 'console_scripts', 'sslyze')()
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/sslyze/__main__.py", line 136, in main
    output_hub.scans_completed(exec_time)
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/sslyze/cli/output_hub.py", line 62, in scans_completed
    out_generator.scans_completed(total_scan_time)
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/sslyze/cli/json_output.py", line 65, in scans_completed
    ensure_ascii=True)
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/home/eric/.pyenv/versions/2.7.11/lib/python2.7/site-packages/sslyze/cli/json_output.py", line 77, in _object_to_json_dict
    elif isinstance(obj, cryptography.hazmat.backends.openssl.x509._Certificate):
AttributeError: 'module' object has no attribute 'openssl'
```

**Comment by nabla-c0d3** [comment]
I just had a discussion about this on the pyca IRC channel and the certificate is bad; the character ":" in "https://" is not allowed in a DNS entry of the SubjectAltName. Other tools may be able to parse it but it is wrong, and the cryptography library just rejects it as bad input. 
Not much I can do on my side, but I am also fine with rejecting certificates that don't follow the (very loosely-defined) spec.

**Comment by konklone** [comment]
That makes sense, and thanks for looking into it. Though, `AttributeError: 'module' object has no attribute 'openssl'` (which only appears on using `--json_out`, as shown above) is less graceful error handling than I'd expect for a malformed cert.

**Comment by nabla-c0d3** [comment]
Yeah it was a different error, that I just fixed.

**Comment by konklone** [comment]
:+1: Thank you!
