### ISSUE TITLE
Isse with TLS certificate serial number parsing

### ISSUE THREAD

**Issue by miradam** [nabla-c0d3/sslyze#233]
\#sslyze --v
1.1.1

\#sslyze --regular localhost:443

 AVAILABLE PLUGINS
 -----------------

  CertificateInfoPlugin
  OpenSslCipherSuitesPlugin
  FallbackScsvPlugin
  OpenSslCcsInjectionPlugin
  SessionRenegotiationPlugin
  HttpHeadersPlugin
  SessionResumptionPlugin
  HeartbleedPlugin
  CompressionPlugin

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   localhost:443                       => 127.0.0.1

Traceback (most recent call last):
  File "/usr/local/bin/sslyze", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/sslyze/__main__.py", line 132, in main
    output_hub.server_scan_completed(CompletedServerScan(server_info, plugin_result_list))
  File "/usr/local/lib/python2.7/dist-packages/sslyze/cli/output_hub.py", line 57, in server_scan_completed
    out_generator.server_scan_completed(server_scan_result)
  File "/usr/local/lib/python2.7/dist-packages/sslyze/cli/console_output.py", line 76, in server_scan_completed
    for line in plugin_result.as_text():
  File "/usr/local/lib/python2.7/dist-packages/sslyze/plugins/certificate_info_plugin.py", line 344, in as_text
    text_output.extend(self._get_basic_certificate_text())
  File "/usr/local/lib/python2.7/dist-packages/sslyze/plugins/certificate_info_plugin.py", line 573, in _get_basic_certificate_text
    self._format_field('Serial Number:', certificate.serial_number),
AttributeError: '_Certificate' object has no attribute 'serial_number'

**Comment by nabla-c0d3** [comment]
What's the certificate on localhost:443?

**Comment by miradam** [comment]
In attachment.
[172.16.10.254-with-chain.crt.zip](https://github.com/nabla-c0d3/sslyze/files/1124840/172.16.10.254-with-chain.crt.zip)

**Comment by cr41g1w** [comment]
I am getting the same error no matter what site I scan, though I am trying to run it on bash on ubuntu on windows.

**Comment by cr41g1w** [comment]
After further testing, only --regular and --certinfo throws the error given above.  All other switches that I have tried work successfully.

**Comment by cr41g1w** [comment]
Commenting out line 573 of sslyze/plugins/certificate_info_plugin.py lets --regular and --certinfo complete successfully, just without getting the certificate serial number.

**Comment by nabla-c0d3** [comment]
I am not able to reproduce this. Which version of the `cryptography` package are you guys using?

**Comment by nabla-c0d3** [comment]
This is caused by very old versions of `cryptography`.
