### ISSUE TITLE
connectivity test raises an exception and hangs

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#300]
When specifying these two targets, an exception is raised by the connectivity test which cannot be printed properly. `sslyze` then hangs on the second target.

### Steps to Reproduce

1. `pip install -U nassl sslyze`
2. `sslyze --regular --xml_out test_sslyze.xml sip.bmrn.com:4443 sip.bmrn.com:5061`

### Expected Results

Recovers from the exception and exits.

### Actual Results

Prints a stacktrace and hangs.

### Output

<pre>

 AVAILABLE PLUGINS
 -----------------

  HeartbleedPlugin
  OpenSslCcsInjectionPlugin
  RobotPlugin
  OpenSslCipherSuitesPlugin
  HttpHeadersPlugin
  SessionResumptionPlugin
  SessionRenegotiationPlugin
  FallbackScsvPlugin
  CompressionPlugin
  CertificateInfoPlugin

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   sip.bmrn.com:4443                      => 12.201.116.24   WARNING: Server requested optional client authentication
Traceback (most recent call last):
  File "/home/hal/env/bin/sslyze", line 11, in <module>
    sys.exit(main())
  File "/home/hal/env/lib/python2.7/site-packages/sslyze/__main__.py", line 92, in main
    output_hub.server_connectivity_test_failed(connectivity_exception)
  File "/home/hal/env/lib/python2.7/site-packages/sslyze/cli/output_hub.py", line 52, in server_connectivity_test_failed
    out_generator.server_connectivity_test_failed(connectivity_error)
  File "/home/hal/env/lib/python2.7/site-packages/sslyze/cli/console_output.py", line 51, in server_connectivity_test_failed
    self._file_to.write(self.SERVER_ERROR_FORMAT.format(host=connectivity_error.server_info.hostname,
AttributeError: 'error' object has no attribute 'server_info'
</pre>

**Comment by postmodern** [comment]
@nabla-c0d3 upgraded to python 3.5.2 and sslyze 1.4.1, and this is still occasionally happening on every other invocation of sslyze against the same target.

`AttributeError: 'ConnectionResetError' object has no attribute 'server_info'`
