### ISSUE TITLE
AttributeError: 'timeout' object has no attribute 'server_info'

### ISSUE THREAD

**Issue by postmodern** [nabla-c0d3/sslyze#315]
### Steps to Reproduce

1. `pip3 install -U nassl=1.1.3 cryptography==2.2.2 sslyze==1.4.1`
2. `sslyze --certinfo --regular secure.stuevesiegel.com:443 secure.stuevesiegel.com:8194`

### Expected Result

Exits

### Actual Result

<pre>
   secure.stuevesiegel.com:443                       => 72.32.166.133 
Traceback (most recent call last):
  File "/home/postmodern/.local/bin/sslyze", line 11, in <module>
    sys.exit(main())
  File "/home/postmodern/.local/lib/python3.6/site-packages/sslyze/__main__.py", line 92, in main
    output_hub.server_connectivity_test_failed(connectivity_exception)
  File "/home/postmodern/.local/lib/python3.6/site-packages/sslyze/cli/output_hub.py", line 52, in server_connectivity_test_failed
    out_generator.server_connectivity_test_failed(connectivity_error)
  File "/home/postmodern/.local/lib/python3.6/site-packages/sslyze/cli/console_output.py", line 51, in server_connectivity_test_failed
    self._file_to.write(self.SERVER_ERROR_FORMAT.format(host=connectivity_error.server_info.hostname,
AttributeError: 'timeout' object has no attribute 'server_info'
</pre>

and the process hangs.

### Additional Info

Python: 3.6.5
nassl: 1.1.3
cryptography: 2.2.2
sslyze: 1.4.1

**Comment by nabla-c0d3** [comment]
Fixed in https://github.com/nabla-c0d3/sslyze/commit/161376923b322819ae41c41b2c3d10f18855d3d3
