### ISSUE TITLE
ImportError: cannot import name timezone

### ISSUE THREAD

**Issue by rishikelltontech** [nabla-c0d3/sslyze#316]
Hi,
Running the below command produces the "ImportError: cannot import name timezone".
python -m sslyze --regular www.yahoo.com:443 www.google.com "[2607:f8b0:400a:807::2004]:443"

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/.virtualenvs/test-env/lib/python2.7/site-packages/sslyze/__main__.py", line 12, in <module>
    from sslyze.concurrent_scanner import ConcurrentScanner
  File "/home/user/.virtualenvs/test-env/local/lib/python2.7/site-packages/sslyze/concurrent_scanner.py", line 12, in <module>
    from sslyze.synchronous_scanner import SynchronousScanner
  File "/home/user/.virtualenvs/test-env/local/lib/python2.7/site-packages/sslyze/synchronous_scanner.py", line 7, in <module>
    from sslyze.plugins.plugins_repository import PluginsRepository
  File "/home/user/.virtualenvs/test-env/local/lib/python2.7/site-packages/sslyze/plugins/plugins_repository.py", line 5, in <module>
    from sslyze.plugins.certificate_info_plugin import CertificateInfoPlugin
  File "/home/user/.virtualenvs/test-env/local/lib/python2.7/site-packages/sslyze/plugins/certificate_info_plugin.py", line 7, in <module>
    from datetime import datetime, timezone
ImportError: cannot import name timezone

Does anyone have idea how to fix this issue?

**Comment by uwe347** [comment]
same problem for me. I am using ubuntu 18.04 and installed:
```
sudo apt install python-pip
pip install --upgrade setuptools
pip install --upgrade sslyze
```
...with no warnings. The tailing lines of this installation were:
```
Successfully built sslyze tls-parser pycparser
Installing collected packages: enum34, typing, nassl, pycparser, cffi, idna, asn1crypto, six, ipaddress, cryptography, tls-parser, sslyze
Successfully installed asn1crypto-0.24.0 cffi-1.11.5 cryptography-2.2.2 enum34-1.1.6 idna-2.6 ipaddress-1.0.22 nassl-1.1.3 pycparser-2.18 six-1.11.0 sslyze-1.4.1 tls-parser-1.2.1 typing-3.6.4
```
Don't know where to look for... Thanks for any hint!

**Comment by nabla-c0d3** [comment]
Fixed in 1.4.2.

**Comment by uwe347** [comment]
Works fine now... Thanks!

**Comment by rishikelltontech** [comment]
Thanks for fixing the issue!!
