### ISSUE TITLE
Http_headers_plugin crashes on HPKP report-to= option

### ISSUE THREAD

**Issue by kravietz** [nabla-c0d3/sslyze#357]
**Describe the bug**
The `http_headers_plugin` crashes when seeing `report-to=` option in the `Public-Key-Pins` header. The option was introduced by [Reporting API](https://w3c.github.io/reporting/#examples) and specifies reporting endpoint to send the HPKP violation reports.

**To Reproduce**
```
Traceback (most recent call last):
  File "/snap/webcookies/x11/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/snap/webcookies/x11/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/snap/webcookies/x11/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/snap/webcookies/current/webcookies/tls_analysis/tasks.py", line 169, in sslyze_check
    plugin_result = scanner.run_scan_command(server_info, command)
  File "/snap/webcookies/x11/lib/python3.6/site-packages/sslyze/synchronous_scanner.py", line 50, in run_scan_command
    return plugin.process_task(server_info, scan_command)
  File "/snap/webcookies/x11/lib/python3.6/site-packages/sslyze/plugins/http_headers_plugin.py", line 55, in process_task
    hpkp_report_only, certificate_chain)
  File "/snap/webcookies/x11/lib/python3.6/site-packages/sslyze/plugins/http_headers_plugin.py", line 239, in __init__
    self.hpkp_header = ParsedHpkpHeader(raw_hpkp_header, hpkp_report_only) if raw_hpkp_header else None
  File "/snap/webcookies/x11/lib/python3.6/site-packages/sslyze/plugins/http_headers_plugin.py", line 168, in __init__
    raise ValueError('Unexpected value in HPKP header: {}'.format(repr(hpkp_directive)))
ValueError: Unexpected value in HPKP header: 'report-to=hpkp"
```

**Expected behavior**
Well, at least not crash :)

**Comment by nabla-c0d3** [comment]
Fix released with v2.0.4.
