### ISSUE TITLE
AttributeError: 'EllipticCurvePublicNumbers' object has no attribute 'n'

### ISSUE THREAD

**Issue by kravietz** [nabla-c0d3/sslyze#358]
Not sure what website generates that:
```
Traceback (most recent call last):
  File "/snap/webcookies/x41/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/snap/webcookies/x41/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/snap/webcookies/x41/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/snap/webcookies/x41/webcookies/tls_analysis/tasks.py", line 172, in sslyze_check
    plugin_result = scanner.run_scan_command(server_info, command)
  File "/snap/webcookies/x41/lib/python3.6/site-packages/sslyze/synchronous_scanner.py", line 50, in run_scan_command
    return plugin.process_task(server_info, scan_command)
  File "/snap/webcookies/x41/lib/python3.6/site-packages/sslyze/plugins/robot_plugin.py", line 189, in process_task
    rsa_params = self._get_rsa_parameters(server_info, cipher_string)
  File "/snap/webcookies/x41/lib/python3.6/site-packages/sslyze/plugins/robot_plugin.py", line 312, in _get_rsa_parameters
    return parsed_cert.public_key().public_numbers().n, parsed_cert.public_key().public_numbers().e
AttributeError: 'EllipticCurvePublicNumbers' object has no attribute 'n'
```

**Comment by nabla-c0d3** [comment]
Fix released with v2.0.4.
