### ISSUE TITLE
Crash seen in Robot Plugin

### ISSUE THREAD

**Issue by blazerguns** [nabla-c0d3/sslyze#361]
**Describe the bug**
The problem is seen when scanning using the robot plugin. In this case the scan is done through APIs rather than command line.

```  synchronous_scanner = SynchronousScanner()
    try:
      scan_result = synchronous_scanner.run_scan_command(server_info, RobotScanCommand())
      if isinstance(scan_result, PluginRaisedExceptionScanResult):
        self.logger.error('Scan command failed: ' + scan_result.scan_command.get_title())
        self.scanSuccess = False
        return final_result
      final_result = {
        "robot": self.inverseit(scan_result. robot_result_enum)
      }
    except ValueError as e:
      self.logger.error('Robot scan failed %s', str(e))
```
This is never a problem most of the time but I encountered this problem when scanning flask app running using gunicorn. It has https enabled and running this plugin failed. I think this is a corner case error handling required.

Stack trace
```
Traceback (most recent call last):
  File "/User/Documents/flash3.6/lib/python3.6/site-packages/sslyze/plugins/robot_plugin.py", line 387, in do_handshake_with_robot
    tls_record, len_consumed = TlsRecordParser.parse_bytes(remaining_bytes)
  File "/User/Documents/flash3.6/lib/python3.6/site-packages/tls_parser/parser.py", line 13, in parse_bytes
    record_header, len_consumed = TlsRecordHeader.from_bytes(raw_bytes)
  File "/User/Documents/flash3.6/lib/python3.6/site-packages/tls_parser/record_protocol.py", line 38, in from_bytes
    raise NotEnoughData()
tls_parser.exceptions.NotEnoughData

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sslscanner.py", line 171, in <module>
    main()
  File "sslscanner.py", line 168, in main
    args.func(args)
  File "sslscanner.py", line 79, in run_scan
    final_result = sslscanner.run_full_scan(args_dict)
  File "/User/webscanner-backend/server/sslscanner.py", line 40, in run_full_scan
    status = plugin_object['func'].run_scan(scanArgs, opts)
  File "/User/webscanner-backend/server/plugins/robot_plugin.py", line 50, in run_scan
    self.result = self.run_robot_check(opts['ssl_endpoint'])
  File "/User/webscanner-backend/server/plugins/robot_plugin.py", line 28, in run_robot_check
    scan_result = synchronous_scanner.run_scan_command(server_info, RobotScanCommand())
  File "/User/Documents/flash3.6/lib/python3.6/site-packages/sslyze/synchronous_scanner.py", line 50, in run_scan_command
    return plugin.process_task(server_info, scan_command)
  File "/User/Documents/flash3.6/lib/python3.6/site-packages/sslyze/plugins/robot_plugin.py", line 217, in process_task
    robot_should_complete_handshake
  File "/User/Documents/flash3.6/lib/python3.6/site-packages/sslyze/plugins/robot_plugin.py", line 281, in _run_oracle_over_threads
    raise exception
  File "/User/Documents/flash3.6/lib/python3.6/site-packages/sslyze/utils/thread_pool.py", line 109, in _work_function
    result = work_function(*args)
  File "/User/Documents/flash3.6/lib/python3.6/site-packages/sslyze/plugins/robot_plugin.py", line 348, in _send_robot_payload
    ssl_connection.connect()
  File "/User/Documents/flash3.6/lib/python3.6/site-packages/sslyze/utils/ssl_connection.py", line 124, in connect
    self.ssl_client.do_handshake()
  File "/User/Documents/flash3.6/lib/python3.6/site-packages/sslyze/plugins/robot_plugin.py", line 391, in do_handshake_with_robot
    raw_ssl_bytes = self._sock.recv(16381)
socket.timeout: timed out
```

**To Reproduce**
1. Install SSLyze using '...' [e.g. pip, git]
2. Run the above code against any standard Flask app with Talisman and gunicron.
3. Run only robot plugin since all other plugins work

**Expected behavior**
The exception should be caught and handled gracefully.

**Python environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python version: 3.6

**Comment by nabla-c0d3** [comment]
The fix was released with v2.1.0.
