### ISSUE TITLE
Permission Denied as a last error

### ISSUE THREAD

**Issue by rootlogic412** [nabla-c0d3/sslyze#363]
Hello, 

I am running sslyze on termux chroot to Ubuntu. 

Traceback (most recent call last):
  File "/usr/local/bin/sslyze", line 11, in <module>
    load_entry_point('sslyze==2.0.6', 'console_scripts', 'sslyze')()
  File "/usr/local/lib/python3.6/dist-packages/sslyze/__main__.py", line 57, in main
    global_scanner = ConcurrentScanner()
  File "/usr/local/lib/python3.6/dist-packages/sslyze/concurrent_scanner.py", line 79, in __init__
    self._task_queue: JoinableQueue = JoinableQueue()  # Processes get tasks from task_queue and
  File "/usr/lib/python3.6/multiprocessing/context.py", line 107, in JoinableQueue
    return JoinableQueue(maxsize, ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 272, in __init__
    Queue.__init__(self, maxsize, ctx=ctx)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
PermissionError: [Errno 13] Permission denied

I also tried adding permissions for all the depency scripts but no success.

**Comment by nabla-c0d3** [comment]
Hello,
This looks like a problem with your environment; https://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied
