### ISSUE TITLE
Certificate error when using it for custom CA (after the new 2.1.1 upgrade)

### ISSUE THREAD

**Issue by agu3rra** [nabla-c0d3/sslyze#376]
**Unable to complete scan for custom CA**
Apparently `sslyze` is no longer able to scan a webserver that contains a custom CA certificate. That's what I can deduce from the error message:

**To Reproduce**
1. Install the latest SSLyze package 2.1.1
2. Run the following command for a webserver using a custom CA certificate:
```shell
python -m sslyze --regular target.com:443
```
```
C:\DEV>python -m sslyze --regular target.com:443



 AVAILABLE PLUGINS
 -----------------

  CertificateInfoPlugin
  OpenSslCcsInjectionPlugin
  RobotPlugin
  SessionRenegotiationPlugin
  HttpHeadersPlugin
  OpenSslCipherSuitesPlugin
  SessionResumptionPlugin
  EarlyDataPlugin
  FallbackScsvPlugin
  CompressionPlugin
  HeartbleedPlugin



 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   target.com:443                       => <IP REMOVED FROM OUTPUT>




Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\agu3rra\AppData\Roaming\Python\Python37\site-packages\sslyze\__main__.py", line 121, in <module>
    main()
  File "C:\Users\agu3rra\AppData\Roaming\Python\Python37\site-packages\sslyze\__main__.py", line 102, in main
    for plugin_result in global_scanner.get_results():
  File "C:\Users\agu3rra\AppData\Roaming\Python\Python37\site-packages\sslyze\concurrent_scanner.py", line 155, in get_results
    result = self._result_queue.get()
  File "C:\Program Files\Python37\lib\multiprocessing\queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\agu3rra\AppData\Roaming\Python\Python37\site-packages\sslyze\plugins\certificate_info_plugin.py", line 388, in __setstate__
    self.__dict__['path_validation_result_list'] = pickle.loads(self.__dict__['path_validation_result_list'])
  File "C:\Users\agu3rra\AppData\Roaming\Python\Python37\site-packages\sslyze\plugins\certificate_info_plugin.py", line 100, in __setstate__
    for cert_pem in self.__dict__['verified_certificate_chain']
TypeError: 'NoneType' object is not iterable
```

**Expected behavior**

**Python environment (please complete the following information):**
 - OS: Windows 10 64 bits
 - Python version: 3.7.0

**Additional context**
I noticed from the release notes on sslyze 2.1.1 that this was an specific item that was changed.
`Fixed bug where SSLyze was unable to build the verified chain for a given server; OpenSSL is now used directly to build the verified chain (#355).` Everything working fine under version 2.0.6 using nassl 2.1.2. CA is detected as not trusted, but sslyze scan completes.

**Comment by nabla-c0d3** [comment]
Fixed in 2.1.2.
