### ISSUE TITLE
invoke test not working

### ISSUE THREAD

**Issue by umair321** [nabla-c0d3/sslyze#399]
Hi, I am not a python developer and using this utility one of my project and directly run on ubuntu 18, after cloning. When trying to invoking tests I am getting following error:

```
Traceback (most recent call last):
  File "/usr/bin/invoke", line 9, in <module>
    load_entry_point('invoke==0.11.1', 'console_scripts', 'invoke')()
  File "/usr/lib/python2.7/dist-packages/invoke/cli.py", line 438, in main
    dispatch(sys.argv)
  File "/usr/lib/python2.7/dist-packages/invoke/cli.py", line 423, in dispatch
    args, collection, parser_contexts = parse(argv, version=version)
  File "/usr/lib/python2.7/dist-packages/invoke/cli.py", line 286, in parse
    collection = loader.load(coll_name) if coll_name else loader.load()
  File "/usr/lib/python2.7/dist-packages/invoke/loader.py", line 51, in load
    module = imp.load_module(name, fd, path, desc)
  File "/var/www/sslyze/tasks.py", line 25
    ctx.run(f'python -m sphinx -v -b html {docs_folder_path} {dst_path}')
```
Please help me how to invoke test successfully. I have already tried with python 3 and 2

**Comment by nabla-c0d3** [comment]
You are using Python 2.7, which is no longer supported by SSLyze; try with Python 3.6.
