### ISSUE TITLE
JSON and XML output with --certinfo flag fail to output for some sites

### ISSUE THREAD

**Issue by warburtr0n** [nabla-c0d3/sslyze#402]
A very small number of public facing websites cause SSLyze to fail when outputting to JSON or XML when examining their certificate using the --certinfo flag. Not outputting to JSON/XML (i.e. using stdout) causes no issues.

An example of a problematic site is shpok.net

**To Reproduce**
1. Install SSLyze v2.1.4
2. **sslyze --certinfo shpok.net** < produces no error
3. **sslyze --certinfo shpok.net --xml_out=-** < produces error...

`Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/sslyze", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/__main__.py", line 121, in main
    output_hub.server_scan_completed(CompletedServerScan(server_info, plugin_result_list))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/cli/output_hub.py", line 72, in server_scan_completed
    out_generator.server_scan_completed(server_scan_result)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/cli/xml_output.py", line 91, in server_scan_completed
    server_scan_node.append(plugin_result.as_xml())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/plugins/certificate_info_plugin.py", line 657, in as_xml
    for cert_xml in self._certificate_chain_to_xml(self.received_certificate_chain):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/plugins/certificate_info_plugin.py", line 627, in _certificate_chain_to_xml
    key_attrs["exponent"] = str(public_key.public_numbers().e)
AttributeError: 'DSAPublicNumbers' object has no attribute 'e'`

4.  **sslyze --certinfo shpok.net --json_out=-** < produces error...

`Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/sslyze", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/__main__.py", line 125, in main
    output_hub.scans_completed(exec_time)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/cli/output_hub.py", line 77, in scans_completed
    out_generator.scans_completed(total_scan_time)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/cli/json_output.py", line 69, in scans_completed
    json_out = json.dumps(self._json_dict, cls=_CustomJsonEncoder, sort_keys=True, indent=4, ensure_ascii=True)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/cli/json_output.py", line 110, in default
    result["publicKey"]["exponent"] = str(public_key.public_numbers().e)
AttributeError: 'DSAPublicNumbers' object has no attribute 'e'`

**Expected behavior**
JSON/XML output should fail gracefully so that if errors occur a placeholder warning is put into the output file instead of producing no output at all.

**Python environment (please complete the following information):**
 - Windows 10 and Ubuntu 18.04
 - Python 3.6.9

**Additional context**
Something very odd is happening here, though I still consider myself a bit of a Python newb so I may be missing something obvious. Playing around with json_output.py it's possible to print (to stdout) the value of 'e' and yet if you try and assign it to a variable it complains that the object has no value of 'e'.

**Comment by nabla-c0d3** [comment]
Thanks for the detailed report !

**Comment by nabla-c0d3** [comment]
Fixed in v3.0.0.
