### ISSUE TITLE
ASN1 to UTF8 conversion failing for some sites when examining certificate

### ISSUE THREAD

**Issue by warburtr0n** [nabla-c0d3/sslyze#403]
A very small number of sites cause SSLyze to fail when trying to examine the cert (either using --certinfo or --regular). The failure seems to be in the Cryptography library.

Example site causing issues: **guanajuato.gob.mx**

**To Reproduce**
1. Install SSLyze using pip
2. Run the following command **sslyze --certinfo guanajuato.gob.mx**
4. See error...

`Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/sslyze", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/__main__.py", line 121, in main
    output_hub.server_scan_completed(CompletedServerScan(server_info, plugin_result_list))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/cli/output_hub.py", line 72, in server_scan_completed
    out_generator.server_scan_completed(server_scan_result)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/cli/console_output.py", line 93, in server_scan_completed
    for line in plugin_result.as_text():
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/plugins/certificate_info_plugin.py", line 474, in as_text
    CertificateUtils.get_name_as_short_text(cert.subject) for cert in self.received_certificate_chain
  File "/home/ubuntu/.local/lib/python3.6/site-packages/sslyze/plugins/certificate_info_plugin.py", line 474, in <listcomp>
    CertificateUtils.get_name_as_short_text(cert.subject) for cert in self.received_certificate_chain
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/x509.py", line 111, in subject
    return _decode_x509_name(self._backend, subject)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 69, in _decode_x509_name
    attribute = _decode_x509_name_entry(backend, entry)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 56, in _decode_x509_name_entry
    value = _asn1_string_to_utf8(backend, data)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/decode_asn1.py", line 761, in _asn1_string_to_utf8
    "Unsupported ASN1 string type. Type: {0}".format(asn1_string.type)
ValueError: Unsupported ASN1 string type. Type: 3`

**Expected behavior**
Although the issue may be in an external library I would expect SSLyze to fail gracefully and display a warning/failure message that could also be captured in JSON/XML output. Currently, if you scan a number of sites and this error occurs all subsequent scanning stops and no JSON/XML output is produced.

**Python environment (please complete the following information):**
 - OS: Windows 10 and Ubuntu 18.03
 - Python version 3.6.9

**Additional context**
As discussed in another thread I have also tried installing sslyze 2.1.4 without dependencies so that I could install the newest Cryptography library (v2.8 I believe). Even with this newest version the problem still occurs.

**Comment by warburtr0n** [comment]
Suspect this may be related only to DSA certificates. From all the sites I've scanned so far no RSA or ECC certs through up issues. Only two DSA ones.

**Comment by nabla-c0d3** [comment]
Thanks for the detailed report !

**Comment by nabla-c0d3** [comment]
Fixed in v3.0.0.
