### ISSUE TITLE
dataclasses is missing in the requirments lists

### ISSUE THREAD

**Issue by blshkv** [nabla-c0d3/sslyze#431]
I"m using the latest version 3.0.2, python3.6
sslyze 
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/sslyze", line 11, in <module>
    load_entry_point('sslyze==3.0.2', 'console_scripts', 'sslyze')()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.6/site-packages/sslyze/__init__.py", line 4, in <module>
    from sslyze.server_setting import (
  File "/usr/lib64/python3.6/site-packages/sslyze/server_setting.py", line 9, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'

**Comment by nabla-c0d3** [comment]
Python 3.6 is no longer supported 😅 - only 3.7 and 3.8.

**Comment by blshkv** [comment]
This is not correct. There is a backport https://github.com/ericvsmith/dataclasses for Python 3.6.

**Comment by nabla-c0d3** [comment]
Yes there is a backport of dataclass but I meant that SSLyze does not support Python 3.6 anymore, Supporting it would require me to build 4 nassl packages on every release, in addition to the existing 8 packages. Not something I can manage, unfortunately.

**Comment by blshkv** [comment]
ok sure noted. I agree, it's about time to move one.
