### ISSUE TITLE
Crash when receiving "tlsv1 alert internal error"

### ISSUE THREAD

**Issue by vbisbest** [nabla-c0d3/sslyze#433]
using version 3.0.2

python3 -m sslyze --tlsv1 lsl.com

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/sslyze/__main__.py", line 84, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/sslyze/__main__.py", line 58, in main
    server_connectivity_info = completed_future.result()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/sslyze/server_connectivity.py", line 170, in perform
    ssl_connection.connect(should_retry_connection=False)
  File "/usr/local/lib/python3.7/site-packages/sslyze/connection_helpers/tls_connection.py", line 282, in connect
    self.ssl_client.do_handshake()
  File "/usr/local/lib/python3.7/site-packages/nassl/ssl_client.py", line 180, in do_handshake
    self._ssl.do_handshake()
nassl._nassl.OpenSSLError: error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error

**Comment by nabla-c0d3** [comment]
Fixed in v3.0.3.

**Comment by nabla-c0d3** [comment]
Fixed in v3.0.3.
