### ISSUE TITLE
BUG_IN_SSYLZE: "missing export tmp dh key"

### ISSUE THREAD

**Issue by OffensityCmsEnum** [nabla-c0d3/sslyze#449]
Scanning TLS 1.0, 1.1 and 1.2 fails for a certain server with the error message "missing export tmp dh key".

**To Reproduce**
```
# sslyze --version
3.0.8
```
```
# sslyze --tlsv1 <redacted>:443
 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   <redacted>:443                       => <redacted>




 SCAN RESULTS FOR <redacted>:443 - <redacted>
 -----------------------------------------------------

 * Error when running --tlsv1:
       You can open an issue at https://github.com/nabla-c0d3/sslyze/issues with the following information:

       * Server: <redacted>:443 - <redacted>
       * Scan command: tls_1_0_cipher_suites

       Traceback (most recent call last):
         File "/usr/local/lib/python3.7/site-packages/sslyze/scanner.py", line 262, in get_results
    server_info, list(completed_scan_jobs)
         File "/usr/local/lib/python3.7/site-packages/sslyze/plugins/openssl_cipher_suites/implementation.py", line 137, in result_for_completed_scan_jobs
    cipher_suite_result = completed_job.result()
         File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
         File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
         File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
         File "/usr/local/lib/python3.7/site-packages/sslyze/plugins/openssl_cipher_suites/_test_cipher_suite.py", line 79, in connect_with_cipher_suite
    ssl_connection.connect()
         File "/usr/local/lib/python3.7/site-packages/sslyze/connection_helpers/tls_connection.py", line 289, in connect
    self.ssl_client.do_handshake()
         File "/usr/local/lib/python3.7/site-packages/nassl/ssl_client.py", line 180, in do_handshake
    self._ssl.do_handshake()
       nassl._nassl.OpenSSLError: error:140820A6:SSL routines:ssl3_check_cert_and_algorithm:missing export tmp dh key



 SCAN COMPLETED IN 0.44 S
 ------------------------
```

I will forward you the target system via email.

**Comment by nabla-c0d3** [comment]
Hello,
I just ran `sslyze --tlsv1` on the server you emailed me, and it worked fine. Are you still seeing this error?
