### ISSUE TITLE
SSLyze fails on CentOS8 / RHEL8

### ISSUE THREAD

**Issue by pufferfish42** [nabla-c0d3/sslyze#458]
When installing sslyze 3 in a virtualenv with Python 3.8 on CentOS8 / RHEL8, running of sslyze fails with the following error:

```
sslyze --certinfo --starttls=ftp <FQDN>:21
Traceback (most recent call last):
  File "<virualenv>bin/sslyze", line 33, in <module>
    sys.exit(load_entry_point('sslyze==3.0.8', 'console_scripts', 'sslyze')())
  File "<virualenv>bin/sslyze", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.8/importlib/metadata.py", line 75, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<virualenv>lib64/python3.8/site-packages/sslyze/__init__.py", line 25, in <module>
    from sslyze.plugins.scan_commands import ScanCommand, ScanCommandType
  File "<virualenv>lib64/python3.8/site-packages/sslyze/plugins/scan_commands.py", line 10, in <module>
    from sslyze.plugins.certificate_info.implementation import CertificateInfoImplementation
  File "<virualenv>lib64/python3.8/site-packages/sslyze/plugins/certificate_info/implementation.py", line 9, in <module>
    from sslyze.plugins.certificate_info._cert_chain_analyzer import (
  File "<virualenv>lib64/python3.8/site-packages/sslyze/plugins/certificate_info/_cert_chain_analyzer.py", line 17, in <module>
    from sslyze.plugins.certificate_info._certificate_utils import extract_dns_subject_alternative_names, get_common_names
  File "<virualenv>lib64/python3.8/site-packages/sslyze/plugins/certificate_info/_certificate_utils.py", line 1, in <module>
    from _sha256 import sha256
ModuleNotFoundError: No module named '_sha256'
```

So I have created a fix and made a pull request to solve this issue.

**To Reproduce**
1. Install SSLyze using 'pip'
2. Run the following command 'sslyze --certinfo --starttls=ftp <FQDN>:21'
4. See error: `ModuleNotFoundError: No module named '_sha256`

**Expected behavior**
SSLyze should just run.

**Python environment (please complete the following information):**
 - OS: CentOS8.2
 - Python version: 3.8

**Additional context**

**Comment by nabla-c0d3** [comment]
Fix released as part of [v3.1.0](https://github.com/nabla-c0d3/sslyze/releases/tag/3.1.0) .
