### ISSUE TITLE
Sslyze v3.0.8, Error when running --sslv2 for a website

### ISSUE THREAD

**Issue by r0oth3x49** [nabla-c0d3/sslyze#459]
**Describe the bug**
I tried to run the latest sslyze against  website from ssllabs `ib.turkmenturkbank.com` and it throws an exception while scanning for SSLv2 ciphers.

**To Reproduce**
1. Installed SSLyze using pip the latest version 3.0.8
2. `sslyze ib.turkmenturkbank.com --sslv2`

**Expected behavior**
Shouldn't through an exception instead it should show either it is supported or not.

**Python environment (please complete the following information):**
 - Ubuntu 20.04 LTS
 - Python 3.8.2
 - SSLyze v3.0.8

**Exception**
```
* Error when running --sslv2:
       You can open an issue at https://github.com/nabla-c0d3/sslyze/issues with the following information:

       * Server: ib.turkmenturkbank.com:443 - 95.85.97.228
       * Scan command: ssl_2_0_cipher_suites

       Traceback (most recent call last):
         File "/*****/lib/python3.8/site-packages/sslyze/scanner.py", line 261, in get_results
    result = implementation_cls.result_for_completed_scan_jobs(
         File "/*****/lib/python3.8/site-packages/sslyze/plugins/openssl_cipher_suites/implementation.py", line 137, in result_for_completed_scan_jobs
    cipher_suite_result = completed_job.result()
         File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
         File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
         File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
         File "/*****/lib/python3.8/site-packages/sslyze/plugins/openssl_cipher_suites/_test_cipher_suite.py", line 79, in connect_with_cipher_suite
    ssl_connection.connect()
         File "/*****/lib/python3.8/site-packages/sslyze/connection_helpers/tls_connection.py", line 289, in connect
    self.ssl_client.do_handshake()
         File "/*****/lib/python3.8/site-packages/nassl/legacy_ssl_client.py", line 96, in do_ssl2_iis_handshake
    self._ssl.do_handshake()
       nassl._nassl.OpenSSLError: error:140EC11B:SSL routines:SSL2_READ_INTERNAL:illegal padding
```

- I have also tested with testssl.sh and ssllabs as usual both were fine.
![Capture](https://user-images.githubusercontent.com/11024397/95458339-77350680-098b-11eb-8d15-beba83eff67f.PNG)

**Comment by nabla-c0d3** [comment]
Fix released as part of [v3.1.0](https://github.com/nabla-c0d3/sslyze/releases/tag/3.1.0) .
