### ISSUE TITLE
Error when running --robot

### ISSUE THREAD

**Issue by andykirwin** [nabla-c0d3/sslyze#461]
**Describe the bug**
Received below error.

```
Traceback (most recent call last):
         File "/usr/lib/python3/dist-packages/sslyze/scanner.py", line 261, in get_results
    result = implementation_cls.result_for_completed_scan_jobs(
         File "/usr/lib/python3/dist-packages/sslyze/plugins/robot/implementation.py", line 92, in result_for_completed_scan_jobs
    server_responses_per_robot_payloads = future.result()
         File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
         File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
         File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
         File "/usr/lib/python3/dist-packages/sslyze/plugins/robot/_robot_tester.py", line 193, in test_robot
    server_responses_per_robot_payloads = _run_oracle_detection(
         File "/usr/lib/python3/dist-packages/sslyze/plugins/robot/_robot_tester.py", line 210, in _run_oracle_detection
    server_response = _send_robot_payload(
         File "/usr/lib/python3/dist-packages/sslyze/plugins/robot/_robot_tester.py", line 298, in _send_robot_payload
    ssl_connection.connect()
         File "/usr/lib/python3/dist-packages/sslyze/connection_helpers/tls_connection.py", line 296, in connect
    raise TlsHandshakeTimedOut(
       sslyze.errors.TlsHandshakeTimedOut
```

**To Reproduce**
1. Run sslyze in Kali 2020.3
2. Run the following command 'ssylze --regular <host:port>'

**Expected behavior**
Unsure

**Python environment (please complete the following information):**
 - OS: Kali 2020.3
 - Python version: 3.8.4

**Additional context**
None

**Comment by nabla-c0d3** [comment]
@andykirwin Can you send me (here or via email) the domain for which this error is happening? Thanks
