### ISSUE TITLE
error:1416F17F:SSL routines:tls_process_server_certificate:wrong certificate type

### ISSUE THREAD

**Issue by blshkv** [nabla-c0d3/sslyze#466]
net-analyzer/sslyze-3.1.0
dev-python/nassl-3.1.0
dev-python/tls_parser-1.2.2

```
bash$ sslyze xxx.com:443        

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.7/sslyze", line 33, in <module>
    sys.exit(load_entry_point('sslyze==3.1.0', 'console_scripts', 'sslyze')())
  File "/usr/lib/python3.7/site-packages/sslyze/__main__.py", line 58, in main
    server_connectivity_info = completed_future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/site-packages/sslyze/server_connectivity.py", line 267, in perform
    ssl_connection.connect(should_retry_connection=False)
  File "/usr/lib/python3.7/site-packages/sslyze/connection_helpers/tls_connection.py", line 290, in connect
    self.ssl_client.do_handshake()
  File "/usr/lib/python3.7/site-packages/nassl/ssl_client.py", line 184, in do_handshake
    self._ssl.do_handshake()
nassl._nassl.OpenSSLError: error:1416F17F:SSL routines:tls_process_server_certificate:wrong certificate type
```

**Comment by nabla-c0d3** [comment]
The fix was released as part of [v4.0.0](https://github.com/nabla-c0d3/sslyze/releases/tag/4.0.0).
