### ISSUE TITLE
Error when running --elliptic_curves

### ISSUE THREAD

**Issue by prangenberg** [nabla-c0d3/sslyze#475]
I just ran sslyze again a local deployment of my application. To be able doing this, I added a entry in the host configuration of the windows machine, which points to 127.0.0.1

Running sslyze produces the following error:

 You can open an issue at https://github.com/nabla-c0d3/sslyze/issues with the following information:

       * Server: l********r.de:13000 - 127.0.0.1
       * Scan command: elliptic_curves

       Traceback (most recent call last):
         File "C:\Users\nabla\Documents\Github\sslyze\sslyze\scanner.py", line 264, in get_results
         File "C:\Users\nabla\Documents\Github\sslyze\sslyze\plugins\elliptic_curves_plugin.py", line 117, in result_for_completed_scan_jobs
         File "C:\Users\nabla\Documents\Github\sslyze\sslyze\plugins\elliptic_curves_plugin.py", line 117, in <listcomp>
         File "C:\Users\nabla\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\_base.py", line 432, in result
         File "C:\Users\nabla\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\_base.py", line 388, in __get_result
         File "C:\Users\nabla\AppData\Local\Programs\Python\Python38\Lib\concurrent\futures\thread.py", line 57, in run
         File "C:\Users\nabla\Documents\Github\sslyze\sslyze\plugins\elliptic_curves_plugin.py", line 161, in _test_curve
         File "C:\Users\nabla\Documents\Github\sslyze\sslyze\connection_helpers\tls_connection.py", line 290, in connect
         File "C:\Users\nabla\.virtualenvs\lol3-kr5HOXoj\lib\site-packages\nassl\ssl_client.py", line 184, in do_handshake
       nassl._nassl.OpenSSLError: error:140943F2:SSL routines:ssl3_read_bytes:sslv3 alert unexpected message

**Comment by nabla-c0d3** [comment]
Hello,
Do you see the same error when run sslyze with no extra command on this host?

**Comment by prangenberg** [comment]
Correct, i ran sslyze without parameter.
I now think this was not a problem of sslyze, as the same certificate is working in a differenz environment / server. (Haproxy)
The setup where this problem occured is a java spring-boot application with the EC certificate embedded in a java keystore. I just moved back to RSA for this application and everything is working now.
