### ISSUE TITLE
Crash with ServerRejectedTlsHandshake when running Heartbleed and CCS commands

### ISSUE THREAD

**Issue by blakeduffey** [nabla-c0d3/sslyze#478]
Windows Server 2019, Python 3.9.1, running against an internal dev instance with a cert issued by our internal CA (may not matter)

Runs for a bit, gives some results, then 

 * Error when running --heartbleed:
       You can open an issue at https://github.com/nabla-c0d3/sslyze/issues with the following information:

       * Server: [redact]:443 - [redact]
       * Scan command: heartbleed

       Traceback (most recent call last):
         File "C:\Program Files\Python39\lib\site-packages\sslyze\scanner.py", line 264, in get_results
    result = implementation_cls.result_for_completed_scan_jobs(
         File "C:\Program Files\Python39\lib\site-packages\sslyze\plugins\heartbleed_plugin.py", line 77, in result_for_completed_scan_jobs
    return HeartbleedScanResult(is_vulnerable_to_heartbleed=completed_scan_jobs[0].result())
         File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 433, in result
    return self.__get_result()
         File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
         File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
         File "C:\Program Files\Python39\lib\site-packages\sslyze\plugins\heartbleed_plugin.py", line 98, in _test_heartbleed
    ssl_connection.connect()
         File "C:\Program Files\Python39\lib\site-packages\sslyze\connection_helpers\tls_connection.py", line 306, in connect
    raise ServerRejectedTlsHandshake(
       sslyze.errors.ServerRejectedTlsHandshake

 * Error when running --openssl_ccs:
       You can open an issue at https://github.com/nabla-c0d3/sslyze/issues with the following information:

       * Server: [redact]:443 - [redact]
       * Scan command: openssl_ccs_injection

       Traceback (most recent call last):
         File "C:\Program Files\Python39\lib\site-packages\sslyze\scanner.py", line 264, in get_results
    result = implementation_cls.result_for_completed_scan_jobs(
         File "C:\Program Files\Python39\lib\site-packages\sslyze\plugins\openssl_ccs_injection_plugin.py", line 78, in result_for_completed_scan_jobs
    return OpenSslCcsInjectionScanResult(is_vulnerable_to_ccs_injection=completed_scan_jobs[0].result())
         File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 433, in result
    return self.__get_result()
         File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
         File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
         File "C:\Program Files\Python39\lib\site-packages\sslyze\plugins\openssl_ccs_injection_plugin.py", line 99, in _test_for_ccs_injection
    ssl_connection.connect()
         File "C:\Program Files\Python39\lib\site-packages\sslyze\connection_helpers\tls_connection.py", line 306, in connect
    raise ServerRejectedTlsHandshake(
       sslyze.errors.ServerRejectedTlsHandshake

running the tool against a different internal host, I get

 * Error when running --openssl_ccs:
       You can open an issue at https://github.com/nabla-c0d3/sslyze/issues with the following information:

       * Server: [redact]:443 - [redact]
       * Scan command: openssl_ccs_injection

       Traceback (most recent call last):
         File "C:\Program Files\Python39\lib\site-packages\sslyze\scanner.py", line 264, in get_results
    result = implementation_cls.result_for_completed_scan_jobs(
         File "C:\Program Files\Python39\lib\site-packages\sslyze\plugins\openssl_ccs_injection_plugin.py", line 78, in result_for_completed_scan_jobs
    return OpenSslCcsInjectionScanResult(is_vulnerable_to_ccs_injection=completed_scan_jobs[0].result())
         File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 433, in result
    return self.__get_result()
         File "C:\Program Files\Python39\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
         File "C:\Program Files\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
         File "C:\Program Files\Python39\lib\site-packages\sslyze\plugins\openssl_ccs_injection_plugin.py", line 99, in _test_for_ccs_injection
    ssl_connection.connect()
         File "C:\Program Files\Python39\lib\site-packages\sslyze\connection_helpers\tls_connection.py", line 306, in connect
    raise ServerRejectedTlsHandshake(
       sslyze.errors.ServerRejectedTlsHandshake

Thoughts?

**Comment by nabla-c0d3** [comment]
Hello,
Does the server support TLS 1.2, or does it only support TLS 1.3? Can you post the output of `python -m sslyze --tlsv1_2 --tlsv1_3 <server>` ? Thanks

**Comment by nabla-c0d3** [comment]
After investigating I think this was the same bug as #472, which I fixed just now as part of [v4.0.2](https://github.com/nabla-c0d3/sslyze/releases/tag/4.0.2). 
Please try this new version and if the bug is still happening, please re-open this issue.
Thanks!
