### ISSUE TITLE
Crash when parsing an OCSP Response with no Next Update

### ISSUE THREAD

**Issue by wondex** [nabla-c0d3/sslyze#481]
**Describe the bug**
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/__main__.py", line 84, in <module>
    main()
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/__main__.py", line 76, in main
    output_hub.server_scan_completed(scan_result)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/cli/output_hub.py", line 53, in server_scan_completed
    out_generator.server_scan_completed(server_scan_result)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/cli/console_output.py", line 75, in server_scan_completed
    for line in cli_connector_cls.result_to_console_output(scan_command_result):
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/plugins/certificate_info/_cli_connector.py", line 92, in result_to_console_output
    result_as_txt.extend(cls._cert_deployment_to_console_output(index, cert_deployment))
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/plugins/certificate_info/_cli_connector.py", line 271, in _cert_deployment_to_console_output
    "Next Update:", cert_deployment.ocsp_response.next_update.date().isoformat()
AttributeError: 'NoneType' object has no attribute 'date'

**To Reproduce**
1. Install SSLyze using using:  pip
2. Run the following command: /opt/rh/rh-python38/root/usr/bin/python3.8 -m sslyze --regular <local company hostname> 
4. See: Describe the bug

**Expected behavior**

**Versions**:
 - OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
 - Python version: 3.8
 - SSLyzeL: 4.0.1

**Additional context**
Already had issues with version 3.1.0, issue #471. Hoped version 4.0.1 would solved this, but another issue occured (don't have this issue with version .
We don't encounter this with an old version (2.0.3).

validated it with openssl, certificated expired (maybe this is an issue in the _cli_connector_.py script? openssl output:
openssl s_client -connect <host>:443 -showcerts | openssl x509 -text
...
         Not Before: Nov 25 13:56:25 2016 GMT
            Not After : Nov 26 13:56:25 2019 GMT
...

**Comment by nabla-c0d3** [comment]
Thanks for the report; it's because of this https://serverfault.com/questions/985493/next-update-is-missing-from-the-ocsp-response
Should be an easy fix.

**Comment by nabla-c0d3** [comment]
Fix released as part of [v4.0.2](https://github.com/nabla-c0d3/sslyze/releases/tag/4.0.2).
