### ISSUE TITLE
"Unexpected value in HSTS header" when running http_headers

### ISSUE THREAD

**Issue by wondex** [nabla-c0d3/sslyze#498]
**Describe the bug**

```
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/scanner.py", line 264, in get_results
    result = implementation_cls.result_for_completed_scan_jobs(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/plugins/http_headers_plugin.py", line 165, in result_for_completed_scan_jobs
    return completed_scan_jobs[0].result()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/plugins/http_headers_plugin.py", line 202, in _retrieve_and_analyze_http_response
    strict_transport_security_header=_parse_hsts_header_from_http_response(http_response),
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/plugins/http_headers_plugin.py", line 267, in _parse_hsts_header_from_http_response
    raise ValueError(f"Unexpected value in HSTS header: {repr(hsts_directive)}")
ValueError: Unexpected value in HSTS header: 'includeSubDomain'
```

**To Reproduce**
Install SSLyze using: pip
Run the following command: /opt/rh/rh-python38/root/usr/bin/python3.8 -m sslyze --regular

**Expected behavior**
Successful scan

**Python environment (please complete the following information):**
OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
Python version: 3.8
SSLyze: 4.0.2

**Comment by nabla-c0d3** [comment]
Fix released as part of [v4.0.3](https://github.com/nabla-c0d3/sslyze/releases/tag/4.0.3).
