### ISSUE TITLE
TLS1.3/ROBOT scan bug with docker

### ISSUE THREAD

**Issue by Dfte** [nabla-c0d3/sslyze#505]
**Describe the bug**
First of all thanks for this library, this is amazing work. When using sslyze from a ubuntu18.04 docker image and scanning for tls1.3 and robot I came across the following stack trace:

```
* Error when running --tlsv1_3:
       You can open an issue at https://github.com/nabla-c0d3/sslyze/issues with the following information:

       * Server: google.com:443 - 216.58.198.206
       * Scan command: tls_1_3_cipher_suites

       Traceback (most recent call last):
         File "/usr/local/lib/python3.8/dist-packages/sslyze/scanner.py", line 178, in queue_scan
    jobs_to_run = implementation_cls.scan_jobs_for_scan_command(
         File "/usr/local/lib/python3.8/dist-packages/sslyze/plugins/openssl_cipher_suites/implementation.py", line 110, in scan_jobs_for_scan_command
    all_cipher_suites_to_test = CipherSuitesRepository.get_all_cipher_suites(cls._tls_version)
         File "/usr/local/lib/python3.8/dist-packages/sslyze/plugins/openssl_cipher_suites/cipher_suites.py", line 72, in get_all_cipher_suites
    ssl_client_modern.set_cipher_list("")  # Disable NON-TLS-1.3 cipher suites
         File "/usr/local/lib/python3.8/dist-packages/nassl/ssl_client.py", line 305, in set_cipher_list
    self._ssl.set_cipher_list(cipher_list)
       nassl._nassl.OpenSSLError: error:1410F0B9:SSL routines:SSL_set_cipher_list:no cipher match


 * Error when running --robot:
       You can open an issue at https://github.com/nabla-c0d3/sslyze/issues with the following information:

       * Server: google.com:443 - 216.58.198.206
       * Scan command: robot

       Traceback (most recent call last):
         File "/usr/local/lib/python3.8/dist-packages/sslyze/scanner.py", line 229, in get_results
    result = implementation_cls.result_for_completed_scan_jobs(
         File "/usr/local/lib/python3.8/dist-packages/sslyze/plugins/robot/implementation.py", line 92, in result_for_completed_scan_jobs
    server_responses_per_robot_payloads = future.result()
         File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
         File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
         File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
         File "/usr/local/lib/python3.8/dist-packages/sslyze/plugins/robot/_robot_tester.py", line 167, in test_robot
    rsa_params = _get_rsa_parameters(server_info, cipher_string)
         File "/usr/local/lib/python3.8/dist-packages/sslyze/plugins/robot/_robot_tester.py", line 225, in _get_rsa_parameters
    ssl_connection = server_info.get_preconfigured_tls_connection()
         File "/usr/local/lib/python3.8/dist-packages/sslyze/server_connectivity.py", line 112, in get_preconfigured_tls_connection
    ssl_connection.ssl_client.set_cipher_list(final_openssl_cipher_string)
         File "/usr/local/lib/python3.8/dist-packages/nassl/ssl_client.py", line 305, in set_cipher_list
    self._ssl.set_cipher_list(cipher_list)
       nassl._nassl.OpenSSLError: error:1410F0B9:SSL routines:SSL_set_cipher_list:no cipher match
```

**To Reproduce**
1. Create a docker container based on ubuntu18.04
2. Install python3.8/pip and sslyze (pip3.8 install sslyze)
4. Launch sslyze google.com:443 --regular

**Expected behavior**
List of the TLS1.3 supported ciphers as well as the result for the ROBOT check

**Python environment (please complete the following information):**
 - Docker (based on ubuntu18.04)
 - Python3.8

**Additional context**
- The library works correctly on my host but not on the docker based on Ubuntu18.04/20.04. Thus I suspect that the issue may come from the docker itself.
- The docker container uses openssl 1.1.1  11 Sep 2018 (Library: OpenSSL 1.1.1g  21 Apr 2020)

Thanks for your help :)

**Comment by nabla-c0d3** [comment]
Hello, can you run `python -m sslyze --version` and post the result here?

**Comment by Dfte** [comment]
Hello!

I ran the command and realised i'm running version 3.0.4. I updated the version and now i have got the following error:

```
Traceback (most recent call last):
  File "Discovery.py", line 122, in <module>
    Discovery()
  File "Discovery.py", line 76, in __init__
    module(args, absolute_path).run()
  File "/Discovery/src/modules/Vhost.py", line 105, in run
    self.ssl_scan()
  File "/Discovery/src/modules/Vhost.py", line 350, in ssl_scan
    if renegociation.accepts_client_renegotiation is True:
AttributeError: 'SessionRenegotiationScanResult' object has no attribute 'accepts_client_renegotiation'
```

I'll take a look at your example code to fix it.
Thanks for your help :)
