### ISSUE TITLE
Can it run on Python 2.7 ?

### ISSUE THREAD

**Issue by sskras** [nabla-c0d3/sslyze#508]
I got an error during a scan run:
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 9: ordinal not in range(128)
```

**To Reproduce**

1. Check the Py version: `Python 2.7.5`
2. [Install pip](https://stackoverflow.com/a/66420587/1025073) accordingly.
3. Installed sslyze using pip.
4. Run the command: `python -m sslyze --regular www.google.com`
5. See error:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/admin2/env/lib/python2.7/site-packages/sslyze/__main__.py", line 129, in <module>
    main()
  File "/home/admin2/env/lib/python2.7/site-packages/sslyze/__main__.py", line 52, in main
    good_server_list, malformed_server_list, args_command_list = sslyze_parser.parse_command_line()
  File "/home/admin2/env/lib/python2.7/site-packages/sslyze/cli/command_line_parser.py", line 172, in parse_command_line
    (args_command_list, args_target_list) = self._parser.parse_args()
  File "/usr/lib64/python2.7/optparse.py", line 1399, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib64/python2.7/optparse.py", line 1439, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/lib64/python2.7/optparse.py", line 1492, in _process_long_opt
    opt = self._match_long_opt(opt)
  File "/usr/lib64/python2.7/optparse.py", line 1477, in _match_long_opt
    return _match_abbrev(opt, self._long_opt)
  File "/usr/lib64/python2.7/optparse.py", line 1687, in _match_abbrev
    if word.startswith(s)]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 9: ordinal not in range(128)
```

**Expected behavior**
If Python 2.7 is supported, it should work.
If it is unsupported, it should state it clear.

**Python environment:**
 - OS: CentOS Linux release 7.9.2009 (Core)
 - Python version: Python 2.7.5

**Additional context**
The the README.md eliminated the Py generation support a year ago:
https://github.com/nabla-c0d3/sslyze/commit/35dab5028e90f32546dae3a11e91dec527c4e1c2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L8

By reading it now it's not clear if the Py 2 is still supported.

**Comment by sskras** [comment]
OK, it seems the problem was quite old version of SSlyze:
`env/lib/python2.7/site-packages/SSLyze-1.4.3.dist-info`

It would be useful to at least recommend somewhere in the README or bugreport template to see if you are using a sufficiently new version...

Just a suggestion.

**Comment by nabla-c0d3** [comment]
The versions of Python that are supported are at the top of the README, displayed as badges.
