### ISSUE TITLE
http_headers - Connection was shut down by peer

### ISSUE THREAD

**Issue by wondex** [nabla-c0d3/sslyze#516]
**Describe the bug**
```
Traceback (most recent call last):
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/scanner.py", line 264, in get_results
    result = implementation_cls.result_for_completed_scan_jobs(
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/plugins/http_headers_plugin.py", line 188, in result_for_completed_scan_jobs
    return completed_scan_jobs[0].result()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/plugins/http_headers_plugin.py", line 213, in _retrieve_and_analyze_http_response
    http_response = HttpResponseParser.parse_from_ssl_connection(ssl_connection.ssl_client)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/connection_helpers/http_response_parser.py", line 27, in parse_from_ssl_connection
    return cls._parse(ssl_conn.read)
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/sslyze/connection_helpers/http_response_parser.py", line 33, in _parse
    response = read_method(4096)
  File "/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/nassl/ssl_client.py", line 233, in read
    decrypted_data = self._ssl.read(size)
nassl._nassl.SslError: Connection was shut down by peer
```

**To Reproduce**
Install SSLyze using: pip
Run the following command: /opt/rh/rh-python38/root/usr/bin/python3.8 -m sslyze --regular

**Expected behavior**
Successful scan

**Python environment (please complete the following information):**
OS: Red Hat Enterprise Linux Server release 7.9 (Maipo)
Python version: 3.8
SSLyzeL: 4.0.4

**Additional context**
command:
openssl s_client -connect host:636 

output:
CONNECTED(00000003) #LDAPS connected without issues

**Comment by nabla-c0d3** [comment]
Fix released as part of v4.1.0.
