### ISSUE TITLE
socket.timeout when testing for TLS 1.3 early data support

### ISSUE THREAD

**Issue by nabla-c0d3** [nabla-c0d3/sslyze#533]
```       Traceback (most recent call last):
         File "/Users/nabla/Documents/tools/sslyze/sslyze/scanner/_mass_scanner.py", line 271, in _generate_result_for_completed_server_scan
    scan_job_results=scan_job_results_for_plugin,
         File "/Users/nabla/Documents/tools/sslyze/sslyze/plugins/early_data_plugin.py", line 81, in result_for_completed_scan_jobs
    return EarlyDataScanResult(supports_early_data=scan_job_results[0].get_result())
         File "/Users/nabla/Documents/tools/sslyze/sslyze/plugins/plugin_base.py", line 62, in get_result
    raise self._exception
         File "/Users/nabla/Documents/tools/sslyze/sslyze/scanner/_jobs_worker_thread.py", line 50, in run
    return_value = job_to_complete.function_to_call(*job_to_complete.function_arguments)
         File "/Users/nabla/Documents/tools/sslyze/sslyze/plugins/early_data_plugin.py", line 93, in _test_early_data_support
    ssl_connection.ssl_client.read(2048)
         File "/Users/nabla/Documents/tools/sslyze/.venv/lib/python3.7/site-packages/nassl/ssl_client.py", line 226, in read
    encrypted_data = self._sock.recv(self._DEFAULT_BUFFER_SIZE)
       socket.timeout: timed out
```

**Comment by nabla-c0d3** [comment]
Fixed in [v5.0.0](https://github.com/nabla-c0d3/sslyze/releases/tag/5.0.0).
