### ISSUE TITLE
ValueError: Should never happen

### ISSUE THREAD

**Issue by devl00p** [nabla-c0d3/sslyze#534]
**Describe the bug**
`ValueError: Should never happen` is raised on `certificate_info` scan command

Here is the output I got:

```
 * Error when running --certinfo:
       You can open an issue at https://github.com/nabla-c0d3/sslyze/issues with the following information:

       * SSLyze version: 4.1.0
       * Server: vpn.technofreudian.com:443 - 82.165.72.151
       * Scan command: certificate_info

       Traceback (most recent call last):
         File "/home/devloop/.local/share/virtualenvs/snip/lib/python3.8/site-packages/sslyze/scanner/_queued_server_scan.py", line 227, in _generate_result_for_completed_server_scan
    result = plugin_implementation_cls.result_for_completed_scan_jobs(server_info, scan_job_results_for_plugin)
         File "/home/devloop/.local/share/virtualenvs/snip/lib/python3.8/site-packages/sslyze/plugins/certificate_info/implementation.py", line 116, in result_for_completed_scan_jobs
    raise ValueError("Should never happen")
       ValueError: Should never happen

 * Error when running --reneg:
       You can open an issue at https://github.com/nabla-c0d3/sslyze/issues with the following information:

       * SSLyze version: 4.1.0
       * Server: vpn.technofreudian.com:443 - 82.165.72.151
       * Scan command: session_renegotiation

       Traceback (most recent call last):
         File "/home/devloop/.local/share/virtualenvs/snip/lib/python3.8/site-packages/sslyze/scanner/_queued_server_scan.py", line 227, in _generate_result_for_completed_server_scan
    result = plugin_implementation_cls.result_for_completed_scan_jobs(server_info, scan_job_results_for_plugin)
         File "/home/devloop/.local/share/virtualenvs/snip/lib/python3.8/site-packages/sslyze/plugins/session_renegotiation_plugin.py", line 95, in result_for_completed_scan_jobs
    result_enum, value = job.get_result()
         File "/home/devloop/.local/share/virtualenvs/snip/lib/python3.8/site-packages/sslyze/plugins/plugin_base.py", line 50, in get_result
    raise self._exception
         File "/home/devloop/.local/share/virtualenvs/snip/lib/python3.8/site-packages/sslyze/scanner/_worker_thread.py", line 50, in run
    return_value = job_to_complete.function_to_call(*job_to_complete.function_arguments)
         File "/home/devloop/.local/share/virtualenvs/snip/lib/python3.8/site-packages/sslyze/plugins/session_renegotiation_plugin.py", line 126, in _test_secure_renegotiation
    ssl_connection.connect()
         File "/home/devloop/.local/share/virtualenvs/snip/lib/python3.8/site-packages/sslyze/connection_helpers/tls_connection.py", line 315, in connect
    raise ServerRejectedTlsHandshake(
       sslyze.errors.ServerRejectedTlsHandshake: vpn.technofreudian.com:443 -> "Server interrupted the TLS handshake".
```

**To Reproduce**
1. Install sslyze==4.1.0
2. Run the following command 'sslyze vpn.technofreudian.com'

**Expected behavior**
Expected certificate information should appear instead of the error

**Python environment:**
 - OS: openSUSE Tumbleweed
 - Python version: 3.8.12

I hope it helps. Keep up the good job, great tool :)

**Comment by nabla-c0d3** [comment]
Fix released as part of [v5.0.6](https://github.com/nabla-c0d3/sslyze/releases/tag/5.0.6).
