### ISSUE TITLE
Error when running --openssl_ccs

### ISSUE THREAD

**Issue by clysel** [nabla-c0d3/sslyze#548]
I have opened an issue at https://github.com/nabla-c0d3/sslyze/issues with the following information:

       * SSLyze version: 5.0.2
       * Server: vejen.mitpas.dk:443 - 77.247.65.55
       * Scan command: openssl_ccs_injection

       Traceback (most recent call last):
         File "/home/chel/.local/lib/python3.10/site-packages/sslyze/scanner/_mass_scanner.py", line 265, in _generate_result_for_completed_server_scan
    scan_cmd_result = plugin_implementation_cls.result_for_completed_scan_jobs(
         File "/home/chel/.local/lib/python3.10/site-packages/sslyze/plugins/openssl_ccs_injection_plugin.py", line 88, in result_for_completed_scan_jobs
    return OpenSslCcsInjectionScanResult(is_vulnerable_to_ccs_injection=scan_job_results[0].get_result())
         File "/home/chel/.local/lib/python3.10/site-packages/sslyze/plugins/plugin_base.py", line 62, in get_result
    raise self._exception
         File "/home/chel/.local/lib/python3.10/site-packages/sslyze/scanner/_jobs_worker_thread.py", line 50, in run
    return_value = job_to_complete.function_to_call(*job_to_complete.function_arguments)
         File "/home/chel/.local/lib/python3.10/site-packages/sslyze/plugins/openssl_ccs_injection_plugin.py", line 109, in _test_for_ccs_injection
    ssl_connection.connect()
         File "/home/chel/.local/lib/python3.10/site-packages/sslyze/connection_helpers/tls_connection.py", line 305, in connect
    raise ServerRejectedTlsHandshake(
       sslyze.errors.ServerRejectedTlsHandshake: vejen.mitpas.dk:443 -> "Server rejected the connection".

**Comment by nabla-c0d3** [comment]
Fixed in [v5.0.5](https://github.com/nabla-c0d3/sslyze/releases/tag/5.0.5)
