### ISSUE TITLE
Crashes in eliptic curves plugin

### ISSUE THREAD

**Issue by improg00n** [nabla-c0d3/sslyze#595]
Crashes in 'Session Renegotiation'.
 * SSLyze version: 5.1.1
       * Server: google.com:443 - 172.217.16.78
       * Scan command: elliptic_curves

       Traceback (most recent call last):
         File "/usr/lib/python3/dist-packages/sslyze/scanner/_mass_scanner.py", line 215, in _generate_scan_jobs_for_server_scan
    jobs_for_scan_cmd = implementation_cls.scan_jobs_for_scan_command(
         File "/usr/lib/python3/dist-packages/sslyze/plugins/elliptic_curves_plugin.py", line 148, in scan_jobs_for_scan_command
    for curve_nid in OpenSslEcNidEnum.get_supported_by_ssl_client()
         File "/usr/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
       AttributeError: get_supported_by_ssl_client

**To Reproduce**
1. Install SSLyze using '...' [e.g. pip, git]
sudo apt upgraded on kali.
3. Run the following command '....'
sslyze google.com
5. See error

**Python environment (please complete the following information):**
 - OS: kali linux
 - Python version: 3.10.9

**Additional context**

**Comment by nabla-c0d3** [comment]
I am unable to reproduce this with Python 3.10 and SSLyze 5.1.1 installed via `pip install sslyze`. There is probably an issue with your environment. The wrong version of nassl might have been installed.
