### ISSUE TITLE
When running sslyze against a LB Server Seeing Traceback while running --elliptic_curves Tests

### ISSUE THREAD

**Issue by srikr** [nabla-c0d3/sslyze#658]
**Describe the bug**
When running sslyze against a LB Server seeing below Traceback

**To Reproduce**
1. In Kali Linux ran the following sslyze command 
`sslyze --targets_in=vs_ip.txt` or `sslyze ip:443`
2. Resulted in following traceback

```
Traceback (most recent call last):
         File "/usr/lib/python3/dist-packages/sslyze/scanner/_mass_scanner.py", line 267, in _generate_result_for_completed_
server_scan
    scan_cmd_result = plugin_implementation_cls.result_for_completed_scan_jobs(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/usr/lib/python3/dist-packages/sslyze/plugins/elliptic_curves_plugin.py", line 169, in result_for_completed_s
can_jobs
    all_ecdh_results = [scan_job.get_result() for scan_job in scan_job_results]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/usr/lib/python3/dist-packages/sslyze/plugins/elliptic_curves_plugin.py", line 169, in <listcomp>
    all_ecdh_results = [scan_job.get_result() for scan_job in scan_job_results]
                        ^^^^^^^^^^^^^^^^^^^^^
         File "/usr/lib/python3/dist-packages/sslyze/plugins/plugin_base.py", line 61, in get_result
    raise self._exception
         File "/usr/lib/python3/dist-packages/sslyze/scanner/_jobs_worker_thread.py", line 50, in run
    return_value = job_to_complete.function_to_call(*job_to_complete.function_arguments)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/usr/lib/python3/dist-packages/sslyze/plugins/elliptic_curves_plugin.py", line 210, in _test_curve
    ssl_connection.ssl_client.set_groups([curve_nid])
         File "/usr/lib/python3/dist-packages/nassl/ssl_client.py", line 455, in set_groups
    self._ssl.set1_groups(supported_groups)
       nassl._nassl.OpenSSLError


```

Below are the Kali Linux Version:  
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2022.3
Codename:       kali-rolling
Seeing following Traceback on running above steps

**Expected behavior**
It should run all the Positive and Negative SSL Tests and provide a Output in JSON File

**Python environment (please complete the following information):**
 - OS: Kali Linux 2022.3
 - Python version: Python 3.11.1
 
**Additional context**
* SSLyze version: 5.0.5
* Server: 100.66.25.87:443 - 100.66.25.87
* Scan command: ScanCommand.ELLIPTIC_CURVES

**Comment by nabla-c0d3** [comment]
This is on an old version of SSLyze (5.0.5) which is no longer maintained.
