### ISSUE TITLE
not a valid TlsHandshakeTypeByte when running --heartbleed

### ISSUE THREAD

**Issue by 3BK** [nabla-c0d3/sslyze#659]
**Describe the bug**
Invalid TlsHandshakeTypeByte when running --heartbleed

**To Reproduce**
1. Install SSLyze using mkdir py39; python3 -mvenv py39; source py39/bin/activate; pip install pip --upgrade; pip install sslyze; 
2. Run the following command sslyze --certinfo_ca_file <ca_file> <target>
 * Error when running --heartbleed:
```
       You can open an issue at https://github.com/nabla-c0d3/sslyze/issues with the following information:

       * SSLyze version: 6.0.0
       * Server: remote_server:443 - <remote ip>
       * Scan command: heartbleed

       Traceback (most recent call last):
         File "py39/lib64/python3.9/site-packages/sslyze/scanner/_mass_scanner.py", line 279, in _generate_result_for_completed_server_scan
    scan_cmd_result = plugin_implementation_cls.result_for_completed_scan_jobs(
         File "py39/lib64/python3.9/site-packages/sslyze/plugins/heartbleed_plugin.py", line 85, in result_for_completed_scan_jobs
    return HeartbleedScanResult(is_vulnerable_to_heartbleed=scan_job_results[0].get_result())
         File "py39/lib64/python3.9/site-packages/sslyze/plugins/plugin_base.py", line 61, in get_result
    raise self._exception
         File "py39/lib64/python3.9/site-packages/sslyze/scanner/_jobs_worker_thread.py", line 59, in run
    return_value = job_to_complete.function_to_call(*job_to_complete.function_arguments)
         File "py39/lib64/python3.9/site-packages/sslyze/plugins/heartbleed_plugin.py", line 106, in _test_heartbleed
    ssl_connection.connect()
         File "py39/lib64/python3.9/site-packages/sslyze/connection_helpers/tls_connection.py", line 298, in connect
    self.ssl_client.do_handshake()
         File "py39/lib64/python3.9/site-packages/sslyze/plugins/heartbleed_plugin.py", line 162, in _do_handshake_with_heartbleed
    tls_record, len_consumed = TlsRecordParser.parse_bytes(remaining_bytes)
         File "py39/lib64/python3.9/site-packages/tls_parser/parser.py", line 15, in parse_bytes
    return TlsHandshakeRecord.from_bytes(raw_bytes)
         File "py39/lib64/python3.9/site-packages/tls_parser/handshake_protocol.py", line 77, in from_bytes
    message, len_consumed_for_message = TlsHandshakeMessage.from_bytes(remaining_bytes)
         File "py39/lib64/python3.9/site-packages/tls_parser/handshake_protocol.py", line 49, in from_bytes
    handshake_type = TlsHandshakeTypeByte(struct.unpack("B", raw_bytes[0:1])[0])
         File "/usr/lib64/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
         File "/usr/lib64/python3.9/enum.py", line 702, in __new__
    raise ve_exc
       ValueError: 111 is not a valid TlsHandshakeTypeByte
```

**Expected behavior**
Clean output.

**Python environment (please complete the following information):**
 - OS: RHEL 9.2
 - Python version: 3.9

**Additional context**

**Comment by 3BK** [comment]
see issue #497 [https://github.com/nabla-c0d3/sslyze/issues/497]

**Comment by nabla-c0d3** [comment]
Closing this as a duplicate of https://github.com/nabla-c0d3/sslyze/issues/497
