### ISSUE TITLE
"ValueError: invalid domain name" when using IPv6

### ISSUE THREAD

**Issue by astrajeriu** [nabla-c0d3/sslyze#675]
* SSLyze version: 6.0.0
       * Server: 0:0:0:0:0:0:0:1:4433 - ::1
       * Scan command: ScanCommand.CERTIFICATE_INFO

       Traceback (most recent call last):
         File "/usr/local/lib/python3.11/dist-packages/sslyze/scanner/_mass_scanner.py", line 279, in _generate_result_for_completed_server_scan
    scan_cmd_result = plugin_implementation_cls.result_for_completed_scan_jobs(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/usr/local/lib/python3.11/dist-packages/sslyze/plugins/certificate_info/implementation.py", line 141, in result_for_completed_scan_jobs
    analysis_result = deployment_analyzer.perform()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/usr/local/lib/python3.11/dist-packages/sslyze/plugins/certificate_info/_cert_chain_analyzer.py", line 191, in perform
    path_validation_result = trust_store.verify_certificate_chain(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/usr/local/lib/python3.11/dist-packages/sslyze/plugins/certificate_info/trust_stores/trust_store.py", line 83, in verify_certificate_chain
    verifier = builder.build_server_verifier(DNSName(server_hostname))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       ValueError: invalid domain name

For the same server, when running against 127.0.0.1:4433, there are no running issues

**Comment by DavidJuanes** [comment]
Same here - had to downgrade to 5.1.3 to get IPv6 functionality working

**Comment by nabla-c0d3** [comment]
Fixed in [v6.1.0](https://github.com/nabla-c0d3/sslyze/releases/tag/6.1.0).
