### ISSUE TITLE
SSLyze on FreeBSD

### ISSUE THREAD

**Issue by mr-gosh** [nabla-c0d3/sslyze#9]
I didn't test it until now - but will it work on FreeBSD?
In the description is it not mentioned...

**Comment by mr-gosh** [comment]
the compile didn't work
___
Stop.                                                                                                                                                           │ 'Tinebase_Exception_Backend_Database' with message 'PDO::MYSQL_ATTR_USE_BUFFERED_QUERY is not defined. Please check PDO extension.' in /usr/local/www/tine20/T
make[1]: stopped in /tmp/nassl/openssl-1.0.2c/crypto                                                                                                            │inebase/Core.php:979\nStack trace:\n#0 /usr/local/www/tine20/Tinebase/Core.php(938): Tinebase_Core::createAndConfigureDbAdapter(Array)\n#1 /usr/local/www/tine2*** Error code 1                                                                                                                                                │0/Tinebase/Core.php(1507): Tinebase_Core::setupDatabaseConnection()\n#2 /usr/local/www/tine20/Tinebase/Config/Abstract.php(154): Tinebase_Core::getDb()\n#3 /us                                                                                                                                                                │r/local/www/tine20/Tinebase/Config/Abstract.php(253): Tinebase_Config_Abstract->get('Tinebase_Authen...', '###NOTSET###')\n#4 /usr/local/www/tine20/Tinebase/LoStop.                                                                                                                                                           │g/Formatter.php(157): Tinebase_Config_Abstract->__isset('Tinebase_Authen...')\n#5 /usr/local/www/tine20/Tinebase/Log.php(41): Tinebase_Log_Formatter->setReplacmake: stopped in /tmp/nassl/openssl-1.0.2c                                                                                                                      │ements()\n#6 /usr/local/www/tine20/Tinebase/Core.php(571): Tinebase_Log->addWriterByConfig(Object(Tinebase_Config_Struct))\n#7 /usr/local/www/tine20/Tinebase/CTraceback (most recent call last):                                                                                                                              │ore.php(1418): Tinebase_Core::setupLogger()\n#8 /usr/local/www/tine20/Tinebase/Core.php(626): Tinebase_Core::getLogger()\n#9 /usr/local/www/tine20/Tinebase/Cor  File "buildAll_unix.py", line 84, in <module>                                                                                                                 │e.php(413): Tinebase_Core::setupCache()\n#10 /usr/local/www/tine20/Tinebase/Server/WebDAV.php(43): Tinebase_Core::initFramework()\n#11 /usr/local/www/tine20/Ti    main()                                                                                                                                                      │nebase/Core.php(251): Tinebase_Server_WebDAV->handle()\n#12 /usr/local/www/tine20/index.php(19): Tinebase_Core::dispatchRequest()\n#13 {main}
  File "buildAll_unix.py", line 62, in main                                                                                                                     │[Wed Jul 08 17:49:14.890767 2015] [:error] [pid 84701] [client 80.187.98.103:10360] PHP Fatal error:  Uncaught exception 'Tinebase_Exception_Backend_Database'     perform_build_task('OPENSSL', OPENSSL_BUILD_TASKS, OPENSSL_DIR)                                                                                             │with message 'PDO::MYSQL_ATTR_USE_BUFFERED_QUERY is not defined. Please check PDO extension.' in /usr/local/www/tine20/Tinebase/Core.php:979\nStack trace:\n#0   File "/tmp/nassl/buildAll_config.py", line 35, in perform_build_task                                                                                          │/usr/local/www/tine20/Tinebase/Core.php(938): Tinebase_Core::createAndConfigureDbAdapter(Array)\n#1 /usr/local/www/tine20/Tinebase/Core.php(1507): Tinebase_Cor    subprocess.check_call(command, shell=True, cwd=cwd)                                                                                                         │e::setupDatabaseConnection()\n#2 /usr/local/www/tine20/Tinebase/Config/Abstract.php(154): Tinebase_Core::getDb()\n#3 /usr/local/www/tine20/Tinebase/Core.php(45  File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call                                                                                        │1): Tinebase_Config_Abstract->get('buildtype', 'RELEASE')\n#4 /usr/local/www/tine20/Tinebase/Core.php(415): Tinebase_Core::setupBuildConstants()\n#5 /usr/local    raise CalledProcessError(retcode, cmd)                                                                                                                      │/www/tine20/Tinebase/Server/WebDAV.php(43): Tinebase_Core::initFramework()\n#6 /usr/local/www/tine20/Tinebase/Core.php(251): Tinebase_Server_WebDAV->handle()\n
subprocess.CalledProcessError: Command 'make' returned non-zero exit status 1

**Comment by mr-gosh** [comment]
the compile script interrupts cause of the platform check - but even if this is replaced through "freebsd10" the compile interrupts with the some error messages:

Stop.                                                                        
make[1]: stopped in /tmp/nassl/openssl-1.0.2c/crypto                         
*** Error code 1                                                             
                                                                             
Stop.                                                                        
make: stopped in /tmp/nassl/openssl-1.0.2c                                   
Traceback (most recent call last):                                           
  File "buildAll_unix.py", line 84, in <module>                              
    main()                                                                   
  File "buildAll_unix.py", line 62, in main                                  
    perform_build_task('OPENSSL', OPENSSL_BUILD_TASKS, OPENSSL_DIR)          
  File "/tmp/nassl/buildAll_config.py", line 35, in perform_build_task       
    subprocess.check_call(command, shell=True, cwd=cwd)                      
  File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call     
    raise CalledProcessError(retcode, cmd)                                   
subprocess.CalledProcessError: Command 'make' returned non-zero exit status 1

**Comment by nabla-c0d3** [comment]
It's the compilation of OpenSSL that fails. Does it compile fine outside of nassl ?
