### ISSUE TITLE
XML serialization invalid token error

### ISSUE THREAD

**Issue by konklone** [nabla-c0d3/sslyze#98]
XML output on a particular domain I found causes an invalid token error on XML serialization:

```
./sslyze.py --regular alert.uat.fns.usda.gov --xml_out=whatever.xml
```

```
Traceback (most recent call last):
  File "./sslyze.py", line 335, in <module>
    main()
  File "./sslyze.py", line 325, in main
    xml_final_pretty = minidom.parseString(tostring(xml_final_doc, encoding='UTF-8'))
  File "/home/eric/.pyenv/versions/2.7.9/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/home/eric/.pyenv/versions/2.7.9/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/home/eric/.pyenv/versions/2.7.9/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 33, column 3684
```

I'm not sure what would be causing this. The full STDOUT output is:

```
CHECKING HOST(S) AVAILABILITY
 -----------------------------

   alert.uat.fns.usda.gov:443          => 199.136.159.248:443



 SCAN RESULTS FOR ALERT.UAT.FNS.USDA.GOV:443 - 199.136.159.248:443
 -----------------------------------------------------------------

  * Deflate Compression:
      OK - Compression disabled          

  * TLSV1_2 Cipher Suites:
      Server rejected all cipher suites.

  * Session Renegotiation:
      Client-initiated Renegotiations:   OK - Rejected
      Secure Renegotiation:              OK - Supported

  * Certificate - Content:
      SHA1 Fingerprint:                  d61a9883a3c58fb41447ea490a026d5790edf3b3
      Common Name:                       alert.uat.fns.usda.gov
      Issuer:                            alert.uat.fns.usda.gov
      Serial Number:                     A059E43E0D05EE6F
      Not Before:                        Feb  7 18:35:00 2012 GMT
      Not After:                         Feb  4 18:35:00 2022 GMT
      Signature Algorithm:               sha1WithRSAEncryption
      Public Key Algorithm:              rsaEncryption
      Key Size:                          4096 bit
      Exponent:                          65537 (0x10001)

  * Certificate - Trust:
      Hostname Validation:               OK - Common Name matches
      Mozilla NSS CA Store (04/2015):    FAILED - Certificate is NOT Trusted: self signed certificate
      Microsoft CA Store (04/2015):      FAILED - Certificate is NOT Trusted: self signed certificate
      Java 6 CA Store (Update 65):       FAILED - Certificate is NOT Trusted: self signed certificate
      Apple CA Store (OS X 10.10.3):     FAILED - Certificate is NOT Trusted: self signed certificate
      Certificate Chain Received:        ['alert.uat.fns.usda.gov']

  * Certificate - OCSP Stapling:
      NOT SUPPORTED - Server did not send back an OCSP response.

  * TLSV1_1 Cipher Suites:
      Server rejected all cipher suites.

  * Session Resumption:
      With Session IDs:                  OK - Supported (5 successful, 0 failed, 0 errors, 5 total attempts).
      With TLS Session Tickets:          NOT SUPPORTED - TLS ticket not assigned.

  * SSLV2 Cipher Suites:
      Server rejected all cipher suites.

  * TLSV1 Cipher Suites:
      Preferred:                       
                 DHE-RSA-AES256-SHA            DH-1024 bits   256 bits      HTTP 200 OK                        
      Accepted:                        
                 DHE-RSA-AES256-SHA            DH-1024 bits   256 bits      HTTP 200 OK                        
                 AES256-SHA                    -              256 bits      HTTP 200 OK                        
                 DHE-RSA-AES128-SHA            DH-1024 bits   128 bits      HTTP 200 OK                        
                 RC4-SHA                       -              128 bits      HTTP 200 OK                        
                 RC4-MD5                       -              128 bits      HTTP 200 OK                        
                 AES128-SHA                    -              128 bits      HTTP 200 OK                        
                 EDH-RSA-DES-CBC3-SHA          DH-1024 bits   112 bits      HTTP 200 OK                        
                 DES-CBC3-SHA                  -              112 bits      HTTP 200 OK                        
                 EDH-RSA-DES-CBC-SHA           DH-1024 bits   56 bits       HTTP 200 OK                        
                 DES-CBC-SHA                   -              56 bits       HTTP 200 OK                        

  * SSLV3 Cipher Suites:
      Preferred:                       
                 DHE-RSA-AES256-SHA            DH-1024 bits   256 bits      HTTP 200 OK                        
      Accepted:                        
                 DHE-RSA-AES256-SHA            DH-1024 bits   256 bits      HTTP 200 OK                        
                 AES256-SHA                    -              256 bits      HTTP 200 OK                        
                 DHE-RSA-AES128-SHA            DH-1024 bits   128 bits      HTTP 200 OK                        
                 RC4-SHA                       -              128 bits      HTTP 200 OK                        
                 RC4-MD5                       -              128 bits      HTTP 200 OK                        
                 AES128-SHA                    -              128 bits      HTTP 200 OK                        
                 EDH-RSA-DES-CBC3-SHA          DH-1024 bits   112 bits      HTTP 200 OK                        
                 DES-CBC3-SHA                  -              112 bits      HTTP 200 OK                        
                 EDH-RSA-DES-CBC-SHA           DH-1024 bits   56 bits       HTTP 200 OK                        
                 DES-CBC-SHA                   -              56 bits       HTTP 200 OK                        

Unhandled exception when processing --heartbleed: 
utils.SSLyzeSSLConnection.SSLHandshakeRejected - TCP / Received RST



 SCAN COMPLETED IN 7.79 S
 ------------------------
```

**Comment by nabla-c0d3** [comment]
Fixed in  bfd7ea4 ; the province name in the certificate is ```Virginia \x08\x08```, which contains illegal characters for XML (\x08).
Thanks!

**Comment by konklone** [comment]
(I think you mean https://github.com/nabla-c0d3/sslyze/commit/4faaecbaf29dddeba8972f5bf94507b5b97c2de8.)

Thank you!

**Comment by nabla-c0d3** [comment]
yes!
